{{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) (not .Values.postgresql.existingSecret)}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb"  }}
  labels:
    {{- include "hapi-fhir-jpaserver.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
