{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.23/report-generator-1.0.23.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.23.jar",
          "url": "report-generator-jvm-1.0.23.jar",
          "size": 279963,
          "sha512": "2f4205544be9f771bc5eed8e1097d3f24425be3fcb9643d0f3b2a24087e1fa891a3c12b76339fca467bcd1023dd02ede2effda1981ce3c2ce4a4920961b15748",
          "sha256": "341c8e114e65fc2a7d7d76b522c5402b99a428beed2ebdfb2e2a66b0a4ad1a2a",
          "sha1": "33ecd41bdcc1cab04bb94d40f31215d705035ce4",
          "md5": "55c9f1218caba0e1af1839e2e616c07c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.23.jar",
          "url": "report-generator-jvm-1.0.23.jar",
          "size": 279963,
          "sha512": "2f4205544be9f771bc5eed8e1097d3f24425be3fcb9643d0f3b2a24087e1fa891a3c12b76339fca467bcd1023dd02ede2effda1981ce3c2ce4a4920961b15748",
          "sha256": "341c8e114e65fc2a7d7d76b522c5402b99a428beed2ebdfb2e2a66b0a4ad1a2a",
          "sha1": "33ecd41bdcc1cab04bb94d40f31215d705035ce4",
          "md5": "55c9f1218caba0e1af1839e2e616c07c"
        }
      ]
    }
  ]
}
