extraConfig: |
  hapi:
    fhir:
      cr_enabled: true
      tester:
        home:
          name: Hello HAPI FHIR
          server_address: "http://fhir-server.127.0.0.1.nip.io/fhir"
          refuse_to_fetch_third_party_urls: true
          fhir_version: R4

ingress:
  enabled: true
  hosts:
    - host: fhir-server.127.0.0.1.nip.io
      pathType: ImplementationSpecific
      paths: ["/"]
