extraVolumes:
  - name: config-kube-root-ca
    configMap:
      name: kube-root-ca.crt
      items:
        - key: ca.crt
          path: ca.crt

extraVolumeMounts:
  - name: config-kube-root-ca
    mountPath: /etc/test
