{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.15/report-generator-1.0.15.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.15.jar",
          "url": "report-generator-jvm-1.0.15.jar",
          "size": 255788,
          "sha512": "5c4d9a76fa787fc20a4504bffe3291b2606c4857e044630737050a1968ae374a30c04024e947fbf7b8ce87e67fa919d7ab0265f445115f7cfce918c617dd30ed",
          "sha256": "628d6463a2fa5d1d9625458d12945cd727b50fc5950a244e6a9d5d30050f34a5",
          "sha1": "6fc2df2675d93a370c86a8c4b90af2953146d932",
          "md5": "7bd217ba0c1c42d064a9e90622ce800c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.15.jar",
          "url": "report-generator-jvm-1.0.15.jar",
          "size": 255788,
          "sha512": "5c4d9a76fa787fc20a4504bffe3291b2606c4857e044630737050a1968ae374a30c04024e947fbf7b8ce87e67fa919d7ab0265f445115f7cfce918c617dd30ed",
          "sha256": "628d6463a2fa5d1d9625458d12945cd727b50fc5950a244e6a9d5d30050f34a5",
          "sha1": "6fc2df2675d93a370c86a8c4b90af2953146d932",
          "md5": "7bd217ba0c1c42d064a9e90622ce800c"
        }
      ]
    }
  ]
}
