{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.15/report-generator-1.0.15.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.15.jar",
          "url": "report-generator-jvm-1.0.15.jar",
          "size": 255787,
          "sha512": "1e191c17ef5e276e7bbaa036a467108aa49aa91136aba20586b917b8c2408797dbc44d0d27b6120402b77e93d55d80042da8ba1385599e3920e6f09f87ef40d8",
          "sha256": "f1f7f298c9cbd41bb4a37f31175e109d5da360cb1cdd2e7777ec128665e9e7f3",
          "sha1": "7c20f0b0c8ae93d7ded1c4bded813bed5753e1ee",
          "md5": "dbb3489323696bf9264f15ae06e3650f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.15.jar",
          "url": "report-generator-jvm-1.0.15.jar",
          "size": 255787,
          "sha512": "1e191c17ef5e276e7bbaa036a467108aa49aa91136aba20586b917b8c2408797dbc44d0d27b6120402b77e93d55d80042da8ba1385599e3920e6f09f87ef40d8",
          "sha256": "f1f7f298c9cbd41bb4a37f31175e109d5da360cb1cdd2e7777ec128665e9e7f3",
          "sha1": "7c20f0b0c8ae93d7ded1c4bded813bed5753e1ee",
          "md5": "dbb3489323696bf9264f15ae06e3650f"
        }
      ]
    }
  ]
}
