{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.15/report-generator-1.0.15.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.15.jar",
          "url": "report-generator-jvm-1.0.15.jar",
          "size": 254629,
          "sha512": "2cd292cf590ee5d184adc43d4af085a348641e59f10298788be295aa8bc54adfc9a49379b188b33876f99efc354e4b50ba32f96c05d720f95352c5ac0cbdf66b",
          "sha256": "e933d09869a580fc862581fc7e9a0a4ddc2c438c31beeb0a6f06bf8ddd862c9d",
          "sha1": "a0afa76a966c00adc06a45179caf2ebc06bce56b",
          "md5": "8cfccb8d5ee8663f7ff27883c7c5ecbe"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.15.jar",
          "url": "report-generator-jvm-1.0.15.jar",
          "size": 254629,
          "sha512": "2cd292cf590ee5d184adc43d4af085a348641e59f10298788be295aa8bc54adfc9a49379b188b33876f99efc354e4b50ba32f96c05d720f95352c5ac0cbdf66b",
          "sha256": "e933d09869a580fc862581fc7e9a0a4ddc2c438c31beeb0a6f06bf8ddd862c9d",
          "sha1": "a0afa76a966c00adc06a45179caf2ebc06bce56b",
          "md5": "8cfccb8d5ee8663f7ff27883c7c5ecbe"
        }
      ]
    }
  ]
}
