sudo: required
dist: trusty
language: java
jdk:
  - openjdk11
before_install:
  - openssl aes-256-cbc -K $encrypted_768cddeffb19_key -iv $encrypted_768cddeffb19_iv
    -in .travis/sa.json.enc -d | docker login -u _json_key --password-stdin https://gcr.io
install:
  - "pip install pytest"
before_script:
  - export MAVEN_SKIP_RC=true
  - sudo chmod -R 777 "$HOME/.m2/repository";
  - sudo chown -R travis:travis "$HOME/.m2/repository";
script:
  - mvn clean install -DskipTests
  - ".travis/test run_server"
  - "make test"
cache:
  directories:
    - "$HOME/.m2/repository"
env:
  global:
    - RELEASE_IMAGE_NAME=gcr.io/freenome-build/inferno-hapifhir
    - MAVEN_OPTS="-Xmx10244M -Xss128M -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=1024M
      -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"
deploy:
  - provider: script
    script: .travis/release
    on:
      branch: master
