FROM ubuntu

ENV PATH="/tmp/apache-maven-3.6.0/bin:${PATH}"

WORKDIR /tmp
RUN apt-get update && \
	apt-get install git -y && \
	apt-get install sed -y && \
	apt-get install wget -y && \
    apt-get install openjdk-11-jdk -y

RUN wget https://www-us.apache.org/dist/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz && tar xzf apache-maven-3.6.2-bin.tar.gz
RUN export PATH=/tmp/apache-maven-3.6.2/bin:${PATH}