@host = http://localhost:8080/matchbox-validator/fhir
### @host = https://test.ahdis.ch/matchbox-order/fhir
### @host = https://test.ahdis.ch/r4


###
GET {{host}}/metadata HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Origin: http://localhost"



### FHIR Tutorial

POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

map "http://ahdis.ch/matchbox/fml/qr2patgender" = "qr2patgender"
uses "http://hl7.org/fhir/StructureDefinition/QuestionnaireResponse" alias QuestionnaireResponse as source
uses "http://hl7.org/fhir/StructureDefinition/Patient" alias Patient as target
group QuestionnaireResponse(source src : QuestionnaireResponse, target tgt : Patient) {
  src.item as item -> tgt as patient then item(item, patient);
}
group item(source src, target tgt: Patient) {
  src.item as item where linkId.value in ('patient.sex') -> tgt.gender = (item.answer.valueString);
}

###
GET {{host}}/StructureMap?url=http://ahdis.ch/matchbox/fml/qr2patgender HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0

###
DELETE {{host}}/StructureMap/qr2patgender HTTP/1.1

###



###
PUT {{host}}/StructureMap/qr2patgender HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

map "http://ahdis.ch/matchbox/fml/qr2patgender" = "qr2patgender"
uses "http://hl7.org/fhir/StructureDefinition/QuestionnaireResponse" alias QuestionnaireResponse as source
uses "http://hl7.org/fhir/StructureDefinition/Patient" alias Patient as target
group QuestionnaireResponse(source src : QuestionnaireResponse, target tgt : Patient) {
  src.item as item -> tgt as patient then item(item, patient);
  src.item as item -> tgt as patient then item(item, patient);
}
group item(source src, target tgt: Patient) {
  src.item as item where linkId.value in ('patient.sex') -> tgt.gender = (item.answer.valueString);
}

### FHIR Tutorial

POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

<StructureMap 
  xmlns="http://hl7.org/fhir">
  <url value="http://ahdis.ch/matchbox/fml/qr2patgender"/>
  <name value="qr2patgender"/>
  <structure>
    <url value="http://hl7.org/fhir/StructureDefinition/QuestionnaireResponse"/>
    <mode value="source"/>
    <alias value="QuestionnaireResponse"/>
  </structure>
  <structure>
    <url value="http://hl7.org/fhir/StructureDefinition/Patient"/>
    <mode value="target"/>
    <alias value="Patient"/>
  </structure>
  <group>
    <name value="QuestionnaireResponse"/>
    <typeMode value="none"/>
    <input>
      <name value="src"/>
      <type value="QuestionnaireResponse"/>
      <mode value="source"/>
    </input>
    <input>
      <name value="tgt"/>
      <type value="Patient"/>
      <mode value="target"/>
    </input>
    <rule>
      <name value="item"/>
      <source>
        <context value="src"/>
        <element value="item"/>
        <variable value="item"/>
      </source>
      <target>
        <contextType value="variable"/>
        <variable value="patient"/>
        <transform value="copy"/>
        <parameter>
          <valueId value="tgt"/>
        </parameter>
      </target>
      <dependent>
        <name value="item"/>
        <variable value="item"/>
        <variable value="patient"/>
      </dependent>
    </rule>
  </group>
  <group>
    <name value="item"/>
    <typeMode value="none"/>
    <input>
      <name value="src"/>
      <mode value="source"/>
    </input>
    <input>
      <name value="tgt"/>
      <type value="Patient"/>
      <mode value="target"/>
    </input>
    <rule>
      <name value="item"/>
      <source>
        <context value="src"/>
        <element value="item"/>
        <variable value="item"/>
        <condition value="linkId.value in ('patient.sex')"/>
      </source>
      <target>
        <context value="tgt"/>
        <contextType value="variable"/>
        <element value="gender"/>
        <transform value="evaluate"/>
        <parameter>
          <valueString value="item.answer.valueString"/>
        </parameter>
      </target>
    </rule>
  </group>
</StructureMap>

###

POST {{host}}/StructureMap/$transform?source=http://ahdis.ch/matchbox/fml/qr2patgender
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

{
  "resourceType": "QuestionnaireResponse",
  "status": "in-progress",
  "item": [
    {
      "linkId": "patient",
      "text": "Patient",
      "item": [
        {
          "linkId": "patient.sex",
          "text": "Geschlecht",
          "answer": [
            {
              "valueString": "female"
            }
          ]
        }
      ]
    }
  ]
}