
### @host = http://localhost:8080/matchbox/fhir
@host = https://test.ahdis.ch/matchbox/fhir
### @host = https://test.ahdis.ch/matchbox/fhir

@example-qr-id = 1378

### Get Capability Statement
GET {{host}}/metadata HTTP/1.1

### Reload all implementation Guides
POST {{host}}/ImplementationGuide/$load-all HTTP/1.1
Content-Type: application/json+fhir

< poc/ig-r4-conceptmaps.json

### Reload all implementation Guides
POST {{host}}/ImplementationGuide HTTP/1.1
Content-Type: application/json+fhir

{
    "resourceType": "ImplementationGuide",
    "name": "ch.fhir.ig.ch-alis",
    "version": "0.2.0",
    "packageId": "ch.fhir.ig.ch-alis",
    "url": "https://www.alis-connect.ch/fhir/package.tgz"
}

### Load Questionnaire (as Bundle)
GET {{host}}/Questionnaire?url=http://fhir.ch/ig/ch-rad-order/Questionnaire/QuestionnaireRadiologyOrder HTTP/1.1
Accept: application/json+fhir

### Populate and get QuestionnaireResponse
POST {{host}}/Questionnaire/$populate HTTP/1.1
Content-Type: application/json+fhir

< poc/populate-params.json

### Save QuestionnaireResponse
POST {{host}}/QuestionnaireResponse HTTP/1.1
Content-Type: application/json+fhir

< poc/example-radorder.json

### Load QuestionnaireResponses
GET {{host}}/QuestionnaireResponse?questionnaire=http://fhir.ch/ig/ch-rad-order/Questionnaire/QuestionnaireRadiologyOrderPoC HTTP/1.1
Accept: application/json+fhir

### Validate QuestionnaireResponse (by sending)
POST {{host}}/QuestionnaireResponse HTTP/1.1
Content-Type: application/json+fhir

< poc/qrbundleattachment.json

### Validate QuestionnaireResponse (from database)
GET {{host}}/QuestionnaireResponse/{{example-qr-id}}/$validate HTTP/1.1
Accept: application/json+fhir

### Extract QuestionnaireResponse from database to Bundle
GET {{host}}/QuestionnaireResponse/{{example-qr-id}}/$extract HTTP/1.1
Accept: application/json+fhir

### Save Bundle
POST {{host}}/Bundle HTTP/1.1
Content-Type: application/json+fhir

< poc/example-bundle.json

### Save Bundle
POST {{host}}/Bundle HTTP/1.1
Content-Type: application/json+fhir

< poc/example-bundle2.json


### Load Bundles
GET {{host}}/Bundle HTTP/1.1

###
DELETE {{host}}/Questionnaire/qrpatientsex
Accept: application/json+fhir


###
GET {{host}}/QuestionnaireResponse/{{example-qr-id}} HTTP/1.1
Accept: application/json+fhir

### Post fixed StructureMap which is not integrated in the implementation guide 
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./poc/OrfQrToBundle.map


### Post fixed StructureMap which is not integrated in the implementation guide 
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./poc/RadOrderQrToBundle.map

### Post fixed Bundle
POST {{host}}/Bundle HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/json+fhir

< ./poc/bundlefailedstore.json


### Get Radiology Order
GET {{host}}/Questionnaire/QuestionnaireRadiologyOrder HTTP/1.1
Accept: application/json+fhir



###
GET {{host}}/ValueSet?url=http://fhir.ch/ig/ch-rad-order/ValueSet/ch-rad-order-caveat-device HTTP/1.1
Accept: application/json+fhir

###
GET {{host}}/ValueSet?url=http://fhir.ch/ig/ch-rad-order/ValueSet/ch-rad-order-caveat-device HTTP/1.1
Accept: application/json+fhir


###
GET {{host}}/ValueSet?url=http://fhir.ch/ig/ch-rad-order/ValueSet/ch-rad-order-caveat-device HTTP/1.1
Accept: application/json+fhir


### Expand ValueSet
GET {{host}}/ValueSet/ch-rad-order-caveat-device/$expand HTTP/1.1
Accept: application/json+fhir

### POC FIX issue https://github.com/ahdis/matchbox/issues/6
PUT {{host}}/ValueSet/ch-rad-order-caveat-device HTTP/1.1
Accept: application/json+fhir
Content-Type: application/json+fhir

< ./poc/ch-rad-order-caveat-device.json

### POC FIX issue https://github.com/ahdis/matchbox/issues/6
PUT {{host}}/ValueSet/ch-rad-order-requested-service HTTP/1.1
Accept: application/json+fhir
Content-Type: application/json+fhir

< ./poc/ch-rad-order-requested-service.json

###
GET {{host}}/Bundle HTTP/1.1
Accept: application/json+fhir


### Post SearchParameter
POST {{host}}/SearchParameter HTTP/1.1
Accept: application/json+fhir
Content-Type: application/json+fhir

< ./poc/searchParameter-placer.json


### Reindicex after searchparameter is founded
POST {{host}}/$mark-all-resources-for-reindexing HTTP/1.1
Accept: application/json+fhir

###
GET {{host}}/Bundle?placer=|urn:oid:2.16.756.5.30.1.145.1.2.3
Accept: application/json+fhir
Cache-Control: no-cache

### receiving all Bundles which are for the domain
GET {{host}}/Bundle?filler=|urn:oid:2.16.756.5.30.1.145.1.2.3
Accept: application/json+fhir
Cache-Control: no-cache

### receiving all Bundles which are for the domain
GET {{host}}/Bundle
Accept: application/json+fhir
Cache-Control: no-cache

###
GET {{host}}/Bundle?placer:not=|urn:oid:2.16.756.5.30.1.145.1.2.3
Accept: application/json+fhir
Cache-Control: no-cache

###
GET {{host}}/Bundle
Accept: application/json+fhir

###
GET {{host}}/Bundle?composition.category=721963009
Accept: application/json+fhir

###
GET {{host}}/Bundle/1552?_fhirpath=Bundle.entry.resource.as(ServiceRequest).identifier.where(type.coding.where(system='http://terminology.hl7.org/CodeSystem/v2-0203' and code='PLAC').exists())
Accept: application/json+fhir



###
GET {{host}}/Bundle?placer
Accept: application/json+fhir

###
GET {{host}}/Bundle
Accept: application/json+fhir

###
GET {{host}}/SearchParameter?url=http://fhir.ch/ig/ch-orf/SearchParameter/placer
Accept: application/json+fhir

###
GET {{host}}/Questionnaire/QuestionnaireRadiologyOrder
Accept: application/json+fhir


###
GET {{host}}/Questionnaire?url=http://fhir.ch/ig/ch-rad-order/Questionnaire/QuestionnaireRadiologyOrder
Accept: application/json+fhir

###
GET https://test.ahdis.ch/matchbox-order/fhir/QuestionnaireResponse/2960

###
GET {{host}}/ConceptMap?url=http://hl7.org/fhir/ConceptMap/cm-administrative-gender-v3
Accept: application/json+fhir

###
GET {{host}}/ConceptMap?url=http://hl7.org/fhir/ConceptMap/cm-administrative-gender-v3
Accept: application/json+fhir

###
GET {{host}}/ConceptMap
Accept: application/json+fhir




### POC fix Upload ConcepMap cm-administrative-gender-v3 from R4 Example
PUT {{host}}/ConceptMap/cm-administrative-gender-v3 HTTP/1.1
Content-Type: application/fhir+json

< ./poc/cm-administrative-gender-v3.json


###
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/cda-fhir-maps/StructureMap/CdaChEmedMedicationCardDocumentToBundle
Accept: application/fhir+xml;fhirVersion=4.0;charset=UTF-8
Content-Type: application/fhir+xml;fhirVersion=4.0;charset=UTF-8

< ./poc/cda-ch-emed-2-7-MedicationCard-UUIDfullUrl.xml

###
DELETE {{host}}/Questionnaire/1432 HTTP/1.1


###
DELETE {{host}}/Task/1279 HTTP/1.1

### Populate and get QuestionnaireResponse
PUT {{host}}/Questionnaire/QuestionnaireRadiologyOrder HTTP/1.1
Content-Type: application/json+fhir

< poc/Questionnaire-QuestionnaireRadiologyOrderPR.json


### Populate and get QuestionnaireResponse
POST {{host}}/Bundle HTTP/1.1
Content-Type: application/json+fhir

< poc/Bundle-DocumentRadiologyOrder-poc.json



###
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/cda-fhir-maps/StructureMap/BundleToCdaChEmedMedicationCardDocument
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./examples/Bundle-2-7-MedicationCard.json



###
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/cda-fhir-maps/StructureMap/BundleToCdaChEmedMedicationCardDocument
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./examples/ChMed16A-Wegmüller_Monika_1943_20210923-1142.json

###
POST {{host}}/StructureMap/$transform?source=http://fhir.ch/ig/cda-fhir-maps/StructureMap/BundleToCdaChEmedMedicationCardDocument
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./examples/ChMed16A-Wegmüller_Monika_1943_20210923-1142-fix.json


###
GET {{host}}/ValueSet/$expand?url=http://fhir.ch/ig/ch-epr-term/ValueSet/DocumentEntry.formatCode HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0


### [ValidationMessage[level=ERROR,type=CODEINVALID,location=Bundle.entry[6].resource.dosage[1].timing.repeat.when[0],message=

# public boolean conformsToProfile(Object appContext, Base item, String url) throws FHIRException {
# The value provided ('MORN') is not in the value set http://hl7.org/fhir/ValueSet/event-timing|4.0.1 (http://hl7.org/fhir/ValueSet/event-timing), and a code is required from this value set) (error message = Validation failed)], 
# ValidationMessage[level=ERROR,type=CODEINVALID,location=Bundle.entry[6].resource.dosage[1].route,message=None of the codings provided are in the value set http://fhir.ch/ig/ch-emed/ValueSet/edqm-routeofadministration (http://fhir.ch/ig/ch-emed/ValueSet/edqm-routeofadministration), and a coding from this value set is required) (codes = urn:oid:0.4.0.127.0.16.1.1.2.1#20053000)], ValidationMessage[level=ERROR,type=CODEINVALID,location=Bundle.entry[6].resource.dosage[1].doseAndRate[0].dose.ofType(Quantity).code,message=The value provided ('732936001') is not in the value set http://fhir.ch/ig/ch-emed/ValueSet/UnitCode (http://fhir.ch/ig/ch-emed/ValueSet/UnitCode), and a code is required from this value set) (error message = Validation failed)]]



### Populate
POST {{host}}/Questionnaire HTTP/1.1
Content-Type: application/json+fhir

< poc/qrsimplerequired.json
