### 
### @host = http://test.ahdis.ch/hapi-fhir-jpavalidator/fhir
### @host = http://test.ahdis.ch/r4
@host = http://localhost:8080/matchbox/fhir
### @host = https://test.ahdis.ch/matchbox/fhir
### @host = http://hapi.fhir.org/baseR4

### @host = https://ehealthsuisse.ihe-europe.net/hapi-fhir-jpavalidator/fhir
### internally mapped to port 8883, not 8080
## @host = http://localhost:8080/hapi-fhir-jpavalidator/fhir
### @host = http://ehealthsuisse.ihe-europe.net:8622/matchbox/fhir

### @host = http://ehealthsuisse.ihe-europe.net/matchbox/fhir
### @host = http://localhost:8080/matchbox/fhir
### @host = http://fhir01.bfh.ch:8080/hapi-fhir-jpaserver/fhir/


### @host = http://ehealthsuisse.ihe-europe.net/matchbox/fhir
### HTTP/1.1 301 Moved Permanently
### Date: Mon, 20 Sep 2021 12:14:36 GMT
### Server: Apache
### Location: https://ehealthsuisse.ihe-europe.net/matchbox/fhir/$validate?profile=http://fhir.ch/ig/ch-rad-order/StructureDefinition/ch-rad-order-document
### Content-Length: 349
### Connection: close
### Content-Type: text/html; charset=iso-8859-1

### <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
### <html><head>
### <title>301 Moved Permanently</title>
### </head><body>
### <h1>Moved Permanently</h1>
### <p>The document has moved <a href="https://ehealthsuisse.ihe-europe.net/matchbox/fhir/$validate?profile=http://fhir.ch/ig/ch-rad-order/StructureDefinition/ch-rad-order-document">here</a>.</p>
### </body></html>


GET {{host}}/metadata HTTP/1.1
Accept: application/fhir+json

###
GET {{host}}/Questionnaire HTTP/1.1
Accept: application/fhir+json

###
POST {{host}}/Questionnaire HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json

< /Users/oliveregger/Documents/github/ch-orf/output/Questionnaire-order-referral-form.json

###
GET {{host}}/StructureDefinition?name=CHEMEDDocumentMedicationCard HTTP/1.1
Accept: application/fhir+json

###
GET {{host}}/ValueSet HTTP/1.1
Accept: application/fhir+json

###
GET {{host}}/ValueSet?url=http://fhir.ch/ig/ch-emed/ValueSet/UnitCode HTTP/1.1
Accept: application/fhir+json

###
GET {{host}}/ValueSet/UnitCode HTTP/1.1
Accept: application/fhir+json

###
GET {{host}}/ValueSet/UnitCode/$expand HTTP/1.1
Accept: application/fhir+json


###
GET {{host}}/StructureDefinition HTTP/1.1
Accept: application/fhir+json


### Validate parameter file
POST {{host}}/$validate?profile=http://hl7.org/fhir/StructureDefinition/Parameters HTTP/.1
Content-Type: application/fhir+xml

< ./examples/parameters.xml


### Validate patient file
POST {{host}}/$validate
Content-Type: application/fhir+xml

< ./examples/patienthtmllang.xml

### Validate patient parameter file
POST {{host}}/$validate
Content-Type: application/fhir+json
Accept: application/fhir+xml

< ./examples/patienthtmllang.json

### Validate parameter file
POST {{host}}/$validate HTTP/.1
Content-Type: application/fhir+xml
Accept: application/fhir+xml

< ./examples/parampatienthtmllang.xml

### Validate parameter file
POST {{host}}/$validate HTTP/.1
Content-Type: application/fhir+json
Accept: application/fhir+xml

< ./examples/parampatienthtmllang.json

### Validate parameter file -- FAILS in 5.2.0, correct 5.5.1
POST {{host}}/$validate HTTP/.1
Content-Type: application/fhir+xml

< ./examples/ParametersSent.xml

### Validate parameter file
POST {{host}}/$validate HTTP/.1
Content-Type: application/fhir+xml

< ./examples/ParametersBroenni.xml

### Validate parameter file: Check validaton errror (FAILS in 5.2.0), correct in 5.3.0-snapshot
### not correct according new spec Invalid Resource target type. Found Person, but expected one of ([PractitionerRole])
POST {{host}}/$validate HTTP/.1
Content-Type: application/fhir+xml
Accept: application/fhir+xml

< ./examples/cdaig.xml


### CH-Core Franz Muster (expected warning: None of the codes provided are in the value set)
POST {{host}}/$validate/?profile=http://hl7.org/fhir/StructureDefinition/Patient HTTP/.1
Content-Type: application/fhir+xml

< ./examples/PatientFranzMuster.xml


### CH-Core Franz Muster )
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-patient
Content-Type: application/fhir+xml

< ./examples/PatientFranzMuster.xml

### CH-Core Franz Muster (No issues detected)
POST {{host}}/$validate?profile=http://hl7.org/fhir/StructureDefinition/Patient HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/PatientFranzMuster.xml

### CH-Core UnknownGender warning (ch-pat-2: gender unknown is currently not used in Switzerland in eCH and the EPR [gender.empty() or (gender != 'unknown')])
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-patient HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/PatientUnknownGender.xml


### CH-Core UnknownGender warning (ch-pat-2: gender unknown is currently not used in Switzerland in eCH and the EPR [gender.empty() or (gender != 'unknown')])
GET {{host}}/Patient/1352/$validate HTTP/1.1
Content-Type: application/fhir+xml



### CH-Core Franz Muster validate with profile inside
POST {{host}}/$validate HTTP/.1
Content-Type: application/fhir+xml

< ./examples/parametersValidate.xml


### CH-Core Bundle
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-document-epr HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/CdaContainingOriginalRepresentationAsPdfA.xml


### CH-ATC one warning: None of the codes provided are in the value set http://hl7.org/fhir/ValueSet/identifier-type (http://hl7.org/fhir/ValueSet/identifier-type), and a code should come from this value set unless it has no suitable code) (codes = urn:uuid:2e82c1f6-a085-4c72-9da3-8640a32e42ab#IHE XDS Metadata)"/>
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-atc/StructureDefinition/DocumentAuditEvent HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/atc-doc-create-rep-pat.xml


### CH-ATC one warning: None of the codes provided are in the value set http://hl7.org/fhir/ValueSet/identifier-type (http://hl7.org/fhir/ValueSet/identifier-type), and a code should come from this value set unless it has no suitable code) (codes = urn:uuid:2e82c1f6-a085-4c72-9da3-8640a32e42ab#IHE XDS Metadata)"/>
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/ch-atc-iti-81-response-sample.xml

### CH-ATC one warning: None of the codes provided are in the value set http://hl7.org/fhir/ValueSet/identifier-type (http://hl7.org/fhir/ValueSet/identifier-type), and a code should come from this value set unless it has no suitable code) (codes = urn:uuid:2e82c1f6-a085-4c72-9da3-8640a32e42ab#IHE XDS Metadata)"/>
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-atc/StructureDefinition/CH-ATC.ITI-81.Response HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/ch-atc-iti-81-response-sample.xml


### CH-EMED bundle
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+json

< ./examples/Medication-1-1-Triatec.json


### CH-EMED bundle
POST {{host}}/Medication/$validate HTTP/1.1
Content-Type: application/fhir+json

< ./examples/Medication-1-1-Triatec.json


### CH-EMED bundle
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationcard HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/2-7-MedicationCard.xml


### Error mesages
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-composition-epr HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/CompositionConfcodeSctError.xml


### ch-epr-mhealth
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-epr-mhealth/StructureDefinition/ch-mhd-providedocumentbundle-comprehensive HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+xml

< ./examples/2-7-BundleProvideDocument.json


### ch-epr-mhealth
POST {{host}}/$validate?profile=http://profiles.ihe.net/ITI/MHD/StructureDefinition/IHE.MHD.Comprehensive.ProvideBundle HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+xml

< ./examples/2-7-BundleProvideDocument.json

### ch-emed
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationcard HTTP/1.1
Content-Type: application/fhir+xml
Accept: application/fhir+xml

< ./examples/2-7-MedicationCard.xml

### ch-emed
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationcard HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

< ./src/test/resources/ehs-439.json

### Failed to parse JSON encoded FHIR content: Content does not appear to be FHIR JSON, first non-whitespace character was: '[' (must be 
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationcard HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

< ./src/test/resources/ehs-431.json


### Resource content has a UTF-8 BOM marking, skipping BOM
POST {{host}}/$validate?profile=http://hl7.org/fhir/StructureDefinition/Patient HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

< ./src/test/resources/ehs-419.json


### cpb-0: Name should be usable as an identifier
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

< /Users/oliveregger/Documents/github/fhir-test-cases/validator/capstmt.json

### warning he Measure 'http://cdcmeasures.example.org/modules/covid19/20200331/numTotBeds' could not be resolved, so no validation can be performed against the Measure"
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

< /Users/oliveregger/Documents/github/fhir-test-cases/validator/mr-covid-mr1.json


###
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

< /Users/oliveregger/Documents/github/fhir-test-cases/validator/parameters-profiled-resource-invalid.json


###
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+xml
Accept: application/fhir+json

< /Users/oliveregger/Documents/github/fhir-test-cases/validator/patient-xver.xml


### Caused by: java.lang.NullPointerException: null
###        at org.hl7.fhir.r5.utils.XVerExtensionManager.status(XVerExtensionManager.java:49)
###        at org.hl7.fhir.validation.instance.InstanceValidator.checkExtension(InstanceValidator.java:1501)
###        at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:4254)
###        at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:4088)
###        at org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:3826)
###        at org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:3713)
###        at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:4819)
### TODO looks like an error in R5 itselft, however strange that it validates directly? different versions


###
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+xml
Accept: application/fhir+json

< /Users/oliveregger/Documents/github/fhir-test-cases/validator/patient-xver-bad.xml


### TODO same error as above, looks like an error in R5 itselft, however strange that it validates directly? different versions


POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

{
	"resourceType": "Patient",
    "extension": [  {
      "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
      "valueString": "Daryl568 Casper496"
    } ],
	"text": {
		"status": "generated",
		"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"de\" lang=\"de\">42\n        </div>"
	}
}

###
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

< /Users/oliveregger/Documents/github/fhir-test-cases/validator/bb-obs-value-is-not-in-valueset.json

### has specified a profile and then I cant do base validation

###
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

< /Users/oliveregger/Documents/github/fhir-test-cases/validator/bundle-duplicate-ids-not.json

### Failed to call access method: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2805 column 2 path $"
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+xml
Accept: application/fhir+json

< /Users/oliveregger/Documents/github/fhir-test-cases/validator/bundle-bad-by-param.xml
### should be 0 not 1
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

< /Users/oliveregger/Documents/github/fhir-test-cases/validator/obs-temp.json
### should be 0 not 1

POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+xml
Accept: application/fhir+json

< /Users/oliveregger/Documents/github/fhir-test-cases/validator/observation-bad-profile.xml
###

GET http://fhir.ch/ig/ch-core/Patient-FranzMuster.xml HTTP/1.1

###

GET https://github.com/hl7ch/ch-core/raw/master/input/examplesNonValid/patient/UnknownGender.xml HTTP/1.1

###
GET https://github.com/hl7ch/ch-core/raw/master/input/examples/bundle/CdaContainingOriginalRepresentationAsPdfA.xml HTTP/1.1

###
GET https://raw.githubusercontent.com/ehealthsuisse/ch-atc/master/input/examples/auditevent/atc-doc-create-rep-pat.xml HTTP/1.1

###
GET https://raw.githubusercontent.com/ehealthsuisse/ch-atc/master/input/examples/bundle/ch-atc-iti-81-response-sample.xml HTTP/1.1

###
GET https://raw.githubusercontent.com/hl7ch/ch-emed/master/input/examples/bundle/2-7-MedicationCard.xml HTTP/1.1


###
GET https://raw.githubusercontent.com/ehealthsuisse/ch-epr-mhealth/master/input/examples/bundle/2-7-BundleProvideDocument.json HTTP/1.1



### CH-Core Franz Muster (No issues detected)
POST {{host}}/DocumentReference/$validate HTTP/1.1
Content-Type: application/fhir+json

< ./examples/DocumentReference-Docu.json

### CH-Core Franz Muster (No issues detected)
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationcard HTTP/1.1
Content-Type: application/fhir+json

< ./examples/medicationCardTest.json

### CH-Core Franz Muster (No issues detected)
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationcard HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/bundleuuid.xml

### CH-Core Franz Muster (No issues detected)
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/bundleuuid.xml


### https://github.com/ahdis/matchbox/issues/15
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationcard HTTP/1.1
Content-Type: application/fhir+json

< ./examples/medicationcardfix.json


### https://github.com/ehealthsuisse/ch-emed/issues/68
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationdispense HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/1-2-MedicationDispense-fr-CH.xml

### CH-Core Franz Muster (No issues detected)
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/bundleuuid.xml


### CH-Core Franz Muster (No issues detected)
### ERROR calling with parameter
### om-3: 'If the resource is contained in another resource, it SHALL be referred to from elsewhere in the resource or SHALL refer to the containing resource' 'If the resource is contained in another resource, it SHALL be referred to from elsewhere in the resource or SHALL refer to the containing resource' ( (unmatched: 1,2,3,4,5,6,7,8))
### see error https://github.com/ahdis/matchbox/issues/11
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/bundleuuid2.xml

###
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-rad-order/StructureDefinition/ch-rad-order-document HTTP/1.1
Content-Type: application/fhir+json; charset=UTF-8

< ./examples/Bundle-DocumentRadiologyOrder.json


###
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-rad-order/StructureDefinition/ch-rad-order-document HTTP/1.1
Content-Type: application/fhir+json; charset=UTF-8

< ./examples/Bundle-DocumentRadiologyOrderAdjusted.json


### where is thsi
GET {{host}}/StructureDefinition?url=http://fhir.ch/ig/ch-allergyintolerance/StructureDefinition/ch-allergyintolerance-condition HTTP/1.1


### where is thsi
GET {{host}}/ImplementationGuide
