### 
### @host = http://test.ahdis.ch/hapi-fhir-jpavalidator/fhir
@host = http://localhost:8080/hapi-fhir-jpavalidator/fhir
### @host = http://localhost:8080/fhir


GET {{host}}/metadata HTTP/1.1
Accept: application/fhir+json

### CH-Core Franz Muster (expected warning: None of the codes provided are in the value set)
POST {{host}}/$validate?profile=http://hl7.org/fhir/StructureDefinition/Parameters HTTP/.1
Content-Type: application/fhir+xml

< ./examples/parameters.xml


### CH-Core Franz Muster (expected warning: None of the codes provided are in the value set)
POST {{host}}/$validate/?profile=http://hl7.org/fhir/StructureDefinition/Patient HTTP/.1
Content-Type: application/fhir+xml

< ./examples/PatientFranzMuster.xml


### CH-Core Franz Muster )
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-patient
Content-Type: application/fhir+xml

< ./examples/PatientFranzMuster.xml

### CH-Core Franz Muster (No issues detected)
POST {{host}}/$validate HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/PatientFranzMuster.xml

### CH-Core UnknownGender warning (ch-pat-2: gender unknown is currently not used in Switzerland in eCH and the EPR [gender.empty() or (gender != 'unknown')])
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-patient HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/PatientUnknownGender.xml


### CH-Core Franz Muster (expected warning: None of the codes provided are in the value set)
POST {{host}}/$validate HTTP/.1
Content-Type: application/fhir+xml

< ./examples/parametersValidate.xml


### CH-Core Bundle
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-document-epr HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/CdaContainingOriginalRepresentationAsPdfA.xml


### CH-ATC one warning: None of the codes provided are in the value set http://hl7.org/fhir/ValueSet/identifier-type (http://hl7.org/fhir/ValueSet/identifier-type), and a code should come from this value set unless it has no suitable code) (codes = urn:uuid:2e82c1f6-a085-4c72-9da3-8640a32e42ab#IHE XDS Metadata)"/>
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-atc/StructureDefinition/DocumentAuditEvent HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/atc-doc-create-rep-pat.xml


### CH-ATC one warning: None of the codes provided are in the value set http://hl7.org/fhir/ValueSet/identifier-type (http://hl7.org/fhir/ValueSet/identifier-type), and a code should come from this value set unless it has no suitable code) (codes = urn:uuid:2e82c1f6-a085-4c72-9da3-8640a32e42ab#IHE XDS Metadata)"/>
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-atc/StructureDefinition/CH-ATC.ITI-81.Response HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/ch-atc-iti-81-response-sample.xml


### CH-EMED bundle
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationcard HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/2-7-MedicationCard.xml


### Error mesages
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-composition-epr HTTP/1.1
Content-Type: application/fhir+xml

< ./examples/CompositionConfcodeSctError.xml


### ch-epr-mhealth
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-epr-mhealth/StructureDefinition/ch-mhd-providedocumentbundle-comprehensive HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+xml

< ./examples/2-7-BundleProvideDocument.json

### ch-epr-mhealth
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-epr-mhealth/StructureDefinition/ch-mhd-comprehensive-documentmanifest HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+xml

< ./examples/DocumentManifest-2-7-DocManMedicationCard.json

### ch-epr-mhealth
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-epr-mhealth/StructureDefinition/ch-mhd-query-comprehensive-documentreference HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+xml

< ./examples/DocumentReference-2-7-DocRefMedicationCard.json


### ch-emed
POST {{host}}/$validate?profile=http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationcard HTTP/1.1
Content-Type: application/fhir+xml
Accept: application/fhir+xml

< ./examples/2-7-MedicationCard.xml

###

### Get the example files for validation, you can use "Save Response Body" and store them into the examples folder

GET http://fhir.ch/ig/ch-core/Patient-FranzMuster.xml HTTP/1.1

###

GET https://github.com/hl7ch/ch-core/raw/master/input/examplesNonValid/patient/UnknownGender.xml HTTP/1.1

###
GET https://github.com/hl7ch/ch-core/raw/master/input/examples/bundle/CdaContainingOriginalRepresentationAsPdfA.xml HTTP/1.1

###
GET https://raw.githubusercontent.com/ehealthsuisse/ch-atc/master/input/examples/auditevent/atc-doc-create-rep-pat.xml HTTP/1.1

###
GET https://raw.githubusercontent.com/ehealthsuisse/ch-atc/master/input/examples/bundle/ch-atc-iti-81-response-sample.xml HTTP/1.1

###
GET https://raw.githubusercontent.com/hl7ch/ch-emed/master/input/examples/bundle/2-7-MedicationCard.xml HTTP/1.1


###
GET https://raw.githubusercontent.com/ehealthsuisse/ch-epr-mhealth/master/input/examples/bundle/2-7-BundleProvideDocument.json HTTP/1.1