{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.9/report-generator-1.0.9.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.9.jar",
          "url": "report-generator-jvm-1.0.9.jar",
          "size": 168728,
          "sha512": "c5cef399d1f1fb35741d739762bd666f760249480ce9bb68f0e52da289a517cfd3a0a31e532d556706182570813383327efe36490859d1050d04a44cfbe3466f",
          "sha256": "8c3e7a689a4cecfabb28548ef2aac9ad34b03a6c2e8cf5dd77a01ddad707fe59",
          "sha1": "b4584b6e43be033165ae56e2703c61db49911668",
          "md5": "c6362a01a388b0776b1f8e725443170c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.9.jar",
          "url": "report-generator-jvm-1.0.9.jar",
          "size": 168728,
          "sha512": "c5cef399d1f1fb35741d739762bd666f760249480ce9bb68f0e52da289a517cfd3a0a31e532d556706182570813383327efe36490859d1050d04a44cfbe3466f",
          "sha256": "8c3e7a689a4cecfabb28548ef2aac9ad34b03a6c2e8cf5dd77a01ddad707fe59",
          "sha1": "b4584b6e43be033165ae56e2703c61db49911668",
          "md5": "c6362a01a388b0776b1f8e725443170c"
        }
      ]
    }
  ]
}
