{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.9/report-generator-1.0.9.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.9.jar",
          "url": "report-generator-jvm-1.0.9.jar",
          "size": 169593,
          "sha512": "f51af9e07fda60970540e7f4299f446e46a924bb273b6af9e38991ab7bd9f76b66ebedc7a3c370a6012766f6dba88ad45e8954a3060645cb6fb496d911d52bfb",
          "sha256": "db76d2a966808bb72f54d38cab6ee2c7811e81078d7eccb3a859af3d56b1d45c",
          "sha1": "4c0de08137b53ce8953c2b6915281311711216f8",
          "md5": "c9d4be7ab6ec32f5d3f6632ad30c6e9a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.9.jar",
          "url": "report-generator-jvm-1.0.9.jar",
          "size": 169593,
          "sha512": "f51af9e07fda60970540e7f4299f446e46a924bb273b6af9e38991ab7bd9f76b66ebedc7a3c370a6012766f6dba88ad45e8954a3060645cb6fb496d911d52bfb",
          "sha256": "db76d2a966808bb72f54d38cab6ee2c7811e81078d7eccb3a859af3d56b1d45c",
          "sha1": "4c0de08137b53ce8953c2b6915281311711216f8",
          "md5": "c9d4be7ab6ec32f5d3f6632ad30c6e9a"
        }
      ]
    }
  ]
}
