{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.9/report-generator-1.0.9.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.9.jar",
          "url": "report-generator-jvm-1.0.9.jar",
          "size": 168713,
          "sha512": "9035bb0dd858e4f622db2f390faa643e459899b70f220a153ebb2d9feecfa9d31d0b5648c063a90fac120bf0bb0b05ff79355558bfae89547012c7dd5d5a8007",
          "sha256": "810665c1dd055812c9760528e885eef308617144b398ea1e65faa3dd097b43a6",
          "sha1": "e016344bc5bb2a9614f6a0c846bf82750d43abf8",
          "md5": "53130f1c710dc4dda89496b6931f69ff"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.9.jar",
          "url": "report-generator-jvm-1.0.9.jar",
          "size": 168713,
          "sha512": "9035bb0dd858e4f622db2f390faa643e459899b70f220a153ebb2d9feecfa9d31d0b5648c063a90fac120bf0bb0b05ff79355558bfae89547012c7dd5d5a8007",
          "sha256": "810665c1dd055812c9760528e885eef308617144b398ea1e65faa3dd097b43a6",
          "sha1": "e016344bc5bb2a9614f6a0c846bf82750d43abf8",
          "md5": "53130f1c710dc4dda89496b6931f69ff"
        }
      ]
    }
  ]
}
