{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.20/report-generator-1.0.20.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.20.jar",
          "url": "report-generator-jvm-1.0.20.jar",
          "size": 322366,
          "sha512": "eee37ad7b9e0d9f196a7afd7f1aa8ae62210f02a359c01cc88e7d9e02ddc9967983e8d339cb3026325834fc6ce166beba6e71b9912949836e14d920a40f3fd58",
          "sha256": "b96c30accee0405a4511c6f5d267921fbc0629fbda5b28e9084aea6edaf39f70",
          "sha1": "429543a9d745be0d1876f891fe743bb279cc11d5",
          "md5": "f7002e55909a649dc93c13b729429730"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.20.jar",
          "url": "report-generator-jvm-1.0.20.jar",
          "size": 322366,
          "sha512": "eee37ad7b9e0d9f196a7afd7f1aa8ae62210f02a359c01cc88e7d9e02ddc9967983e8d339cb3026325834fc6ce166beba6e71b9912949836e14d920a40f3fd58",
          "sha256": "b96c30accee0405a4511c6f5d267921fbc0629fbda5b28e9084aea6edaf39f70",
          "sha1": "429543a9d745be0d1876f891fe743bb279cc11d5",
          "md5": "f7002e55909a649dc93c13b729429730"
        }
      ]
    }
  ]
}
