{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.13/report-generator-1.0.13.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator.klib",
          "url": "report-generator-native-1.0.13.klib",
          "size": 46446,
          "sha512": "f1c822f1f64abf5cb8042f28cb5b74566892880a834fa05ba3f9ed6a9240ace4938318c60ea76712a08a2438bebf2f501c9a7a3bb759ff74d357263a1c518041",
          "sha256": "3a70cf671a501b49914b66d2da746c5575e26564765e3f2c13ca7c884ce40a3f",
          "sha1": "b105263ce5775e387c96e9bd627226247195d8e0",
          "md5": "1926624bd8d918c82469f775592fd143"
        }
      ]
    },
    {
      "name": "nativeMetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-native-1.0.13-metadata.jar",
          "url": "report-generator-native-1.0.13-metadata.jar",
          "size": 261,
          "sha512": "6dcbec89471b84477c69212b37f7dc53cb417144f21543b4f5e40d1382fa707ae9d2cfdd9d862aa4e6be014029b1bfcce709319f88d501b465dd19cf0f5f06b2",
          "sha256": "8b5f2140c2f0cc05ff5fcf7ac928dd5e84d9af186a7dfc0160979a3d06c2694d",
          "sha1": "518d7682af01044987d9472d941a09111ebad163",
          "md5": "ac06e4d642133085fcce49d14aa3e6ca"
        }
      ]
    }
  ]
}
