{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.14/report-generator-1.0.14.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.14.jar",
          "url": "report-generator-jvm-1.0.14.jar",
          "size": 217707,
          "sha512": "ece627ca80b00fbdba248f3348bef968bbdd9676afe30cef42f5bde10dcfbfea79a43d7a66ef3cd71242e7b72584dcc4298a96e904bbdcda57f00bac3a161a41",
          "sha256": "dadda27e17825b16bce6101f78aced5ae031be9928287c105e59c253fb9c0a7a",
          "sha1": "c828a42e452616e2e8d1e8fe5795585e488db2ab",
          "md5": "4905fcfc0c675d481eb07b5db71dc55b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.14.jar",
          "url": "report-generator-jvm-1.0.14.jar",
          "size": 217707,
          "sha512": "ece627ca80b00fbdba248f3348bef968bbdd9676afe30cef42f5bde10dcfbfea79a43d7a66ef3cd71242e7b72584dcc4298a96e904bbdcda57f00bac3a161a41",
          "sha256": "dadda27e17825b16bce6101f78aced5ae031be9928287c105e59c253fb9c0a7a",
          "sha1": "c828a42e452616e2e8d1e8fe5795585e488db2ab",
          "md5": "4905fcfc0c675d481eb07b5db71dc55b"
        }
      ]
    }
  ]
}
