{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-metadata-1.0.16-all.jar",
          "url": "report-generator-1.0.16-all.jar",
          "size": 14145,
          "sha512": "3270656be41a0e12e76d9a3a7790a4db12436df54c635a46884a320200d51103c69e066b757cf3cc9712b3c960ed0c83e7e3bc12f30a716bee997ae081dc8549",
          "sha256": "9d27744d82acb89424e90f1df04cc419a7d7c3e830b7e19b0e1b7ef8ca4f94f8",
          "sha1": "a9000644373f5ea94974a8218b1e2aa8ccfddd40",
          "md5": "63eb075bd718141bb16fe346e4bbeeda"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-1.0.16.jar",
          "url": "report-generator-1.0.16.jar",
          "size": 39227,
          "sha512": "cc60b6cf890ffae84b9fcd9003911e6e41e8bd7c92e7d6e6a5a81e7991c4ac575139b1b3f4b3d63484d103924dc14f65f10b548eaf1873098c3a84e65356673e",
          "sha256": "61816edc67d7d3b06e28cc9a7843d304ef5093241553e9d16e7e935cd246271d",
          "sha1": "80f98da78a79be72293035b42bd5cabc035569c2",
          "md5": "2034b2d75b4dda5fc75cfba28b18300d"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../report-generator-js/1.0.16/report-generator-js-1.0.16.module",
        "group": "com.iprd.report",
        "module": "report-generator-js",
        "version": "1.0.16"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../report-generator-js/1.0.16/report-generator-js-1.0.16.module",
        "group": "com.iprd.report",
        "module": "report-generator-js",
        "version": "1.0.16"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../report-generator-js/1.0.16/report-generator-js-1.0.16.module",
        "group": "com.iprd.report",
        "module": "report-generator-js",
        "version": "1.0.16"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../report-generator-js/1.0.16/report-generator-js-1.0.16.module",
        "group": "com.iprd.report",
        "module": "report-generator-js",
        "version": "1.0.16"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../report-generator-jvm/1.0.16/report-generator-jvm-1.0.16.module",
        "group": "com.iprd.report",
        "module": "report-generator-jvm",
        "version": "1.0.16"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../report-generator-jvm/1.0.16/report-generator-jvm-1.0.16.module",
        "group": "com.iprd.report",
        "module": "report-generator-jvm",
        "version": "1.0.16"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../report-generator-native/1.0.16/report-generator-native-1.0.16.module",
        "group": "com.iprd.report",
        "module": "report-generator-native",
        "version": "1.0.16"
      }
    },
    {
      "name": "nativeMetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../report-generator-native/1.0.16/report-generator-native-1.0.16.module",
        "group": "com.iprd.report",
        "module": "report-generator-native",
        "version": "1.0.16"
      }
    }
  ]
}
