{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-metadata-1.0.17-all.jar",
          "url": "report-generator-1.0.17-all.jar",
          "size": 13610,
          "sha512": "f20b5bac724d7174dd351b9b77b9780f60505afab27962f04e0e0e3815fa321bc0769f61022ec594fd5c6df37e97ae75d513df09f842b1a697da0e661050ad0f",
          "sha256": "70245d2fc3599d5192552e6eac8141fcfd7c0efafab2ecccf87e079d43578f91",
          "sha1": "84d33fe16c6245f4e94683bf010f772bbb286795",
          "md5": "f59f1d7873b1b358327709e153a44332"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-1.0.17.jar",
          "url": "report-generator-1.0.17.jar",
          "size": 35704,
          "sha512": "417897b35a3aab74d69e97df34abf79eca7fcede464a1a07fb9b7d46a801a4c7e4a51e8f412a719358edfd305f46795512d35bcef4802544676a69b144f0462f",
          "sha256": "72906d7af12fb4f8e9fd3b3b1897e5ba9104c86aa07337581018b4ed37d9857a",
          "sha1": "a385bea236bb4d8f589188c44cd50639b141e0aa",
          "md5": "febf946809d2863918f91ce718bd50cd"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../report-generator-js/1.0.17/report-generator-js-1.0.17.module",
        "group": "com.iprd.report",
        "module": "report-generator-js",
        "version": "1.0.17"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../report-generator-js/1.0.17/report-generator-js-1.0.17.module",
        "group": "com.iprd.report",
        "module": "report-generator-js",
        "version": "1.0.17"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../report-generator-js/1.0.17/report-generator-js-1.0.17.module",
        "group": "com.iprd.report",
        "module": "report-generator-js",
        "version": "1.0.17"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../report-generator-js/1.0.17/report-generator-js-1.0.17.module",
        "group": "com.iprd.report",
        "module": "report-generator-js",
        "version": "1.0.17"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../report-generator-jvm/1.0.17/report-generator-jvm-1.0.17.module",
        "group": "com.iprd.report",
        "module": "report-generator-jvm",
        "version": "1.0.17"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../report-generator-jvm/1.0.17/report-generator-jvm-1.0.17.module",
        "group": "com.iprd.report",
        "module": "report-generator-jvm",
        "version": "1.0.17"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../report-generator-native/1.0.17/report-generator-native-1.0.17.module",
        "group": "com.iprd.report",
        "module": "report-generator-native",
        "version": "1.0.17"
      }
    },
    {
      "name": "nativeMetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../report-generator-native/1.0.17/report-generator-native-1.0.17.module",
        "group": "com.iprd.report",
        "module": "report-generator-native",
        "version": "1.0.17"
      }
    }
  ]
}
