{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.14/report-generator-1.0.14.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator.klib",
          "url": "report-generator-native-1.0.14.klib",
          "size": 46607,
          "sha512": "25d13f96bf3f127c6195e804cd31750f520ea061102fa7fbae271f532f4a3f35aa8b55a2c4a1a5bde85b7cd508d39c65eb039a9f5f037824f796761956fc3b78",
          "sha256": "947be5ddbf2a5530702e6acd8c323c43bd7836149112d6d73e80d6a616eea1c2",
          "sha1": "3b1fce4f30a078fb47d03bd937778ba70b51c42a",
          "md5": "904708588639817ed79e8d2ab9ada2cc"
        }
      ]
    },
    {
      "name": "nativeMetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-native-1.0.14-metadata.jar",
          "url": "report-generator-native-1.0.14-metadata.jar",
          "size": 261,
          "sha512": "36219bbffdd877f2cce1c35a2bf69a0f9b03ce3c401b4a9e458f85689efd4807a13a444a0898220fb60971ff542da549f6a5b63eaf671dc516e2b9862064b6a0",
          "sha256": "0a89b5b108e4866ddcff683e8cdf777d9aa0e5bfeb589cd42df02ab2733c0690",
          "sha1": "b7f912cdf0b3ec9887e23149d5b8fd05124290f6",
          "md5": "a9dc1c60509a2015036968e5191653a9"
        }
      ]
    }
  ]
}
