{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.24/report-generator-1.0.24.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.24.jar",
          "url": "report-generator-jvm-1.0.24.jar",
          "size": 281265,
          "sha512": "ce018b16c59e884b0356ff99c2cedb4c2f9d3d7a2e9a411a4158b77645898a77024bea37f5f1130587e1d367d1cacec12672c4781216b59753cb1ceb6b97bbf7",
          "sha256": "172896aa7f0a281fd7285d5a519b9d7d36fa22be7a0e13213b691f7fd70ac69e",
          "sha1": "2bccb2da322b83fd026e638f73390359c40e4844",
          "md5": "143d91701d26a0c0a3ce85108ee4452d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.24.jar",
          "url": "report-generator-jvm-1.0.24.jar",
          "size": 281265,
          "sha512": "ce018b16c59e884b0356ff99c2cedb4c2f9d3d7a2e9a411a4158b77645898a77024bea37f5f1130587e1d367d1cacec12672c4781216b59753cb1ceb6b97bbf7",
          "sha256": "172896aa7f0a281fd7285d5a519b9d7d36fa22be7a0e13213b691f7fd70ac69e",
          "sha1": "2bccb2da322b83fd026e638f73390359c40e4844",
          "md5": "143d91701d26a0c0a3ce85108ee4452d"
        }
      ]
    }
  ]
}
