{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.17/report-generator-1.0.17.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.17.jar",
          "url": "report-generator-jvm-1.0.17.jar",
          "size": 251748,
          "sha512": "b401e57e847b1a0fc890ce5ea0285f4925dca89ff8ab363ae92efd13e46641080bb0dfe0622cf49d6a125b9789bfbc0c3cafcb1aacfb8f930abe08318358e136",
          "sha256": "46b5918bd795a0f3000b1f917cf89bc4be1488809295d4df99df7df16931b64b",
          "sha1": "86ae0ee3f5c58349a38435b3661d7376c72f91b2",
          "md5": "86ba81846f5bc7b57e449e11069c3f16"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.17.jar",
          "url": "report-generator-jvm-1.0.17.jar",
          "size": 251748,
          "sha512": "b401e57e847b1a0fc890ce5ea0285f4925dca89ff8ab363ae92efd13e46641080bb0dfe0622cf49d6a125b9789bfbc0c3cafcb1aacfb8f930abe08318358e136",
          "sha256": "46b5918bd795a0f3000b1f917cf89bc4be1488809295d4df99df7df16931b64b",
          "sha1": "86ae0ee3f5c58349a38435b3661d7376c72f91b2",
          "md5": "86ba81846f5bc7b57e449e11069c3f16"
        }
      ]
    }
  ]
}
