{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.17/report-generator-1.0.17.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.17.jar",
          "url": "report-generator-jvm-1.0.17.jar",
          "size": 293927,
          "sha512": "f6b9b1bdff5c82642a16bf1555cba68fc8d5c53c46701a48e17f76d7d38777d6e858def94dbeebbe214ac2af6f79a7e68782c48a3117745d78fdc70910f3264b",
          "sha256": "3af4569613230a999065cdbb34a420b565e737a7627d543ffb21c83a4d7af689",
          "sha1": "fd3f4cad361c517418174b792974e0307bb0177a",
          "md5": "e18a2f269a4348026a6a2f479fb9a038"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.17.jar",
          "url": "report-generator-jvm-1.0.17.jar",
          "size": 293927,
          "sha512": "f6b9b1bdff5c82642a16bf1555cba68fc8d5c53c46701a48e17f76d7d38777d6e858def94dbeebbe214ac2af6f79a7e68782c48a3117745d78fdc70910f3264b",
          "sha256": "3af4569613230a999065cdbb34a420b565e737a7627d543ffb21c83a4d7af689",
          "sha1": "fd3f4cad361c517418174b792974e0307bb0177a",
          "md5": "e18a2f269a4348026a6a2f479fb9a038"
        }
      ]
    }
  ]
}
