{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.26/report-generator-1.0.26.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.26.jar",
          "url": "report-generator-jvm-1.0.26.jar",
          "size": 284650,
          "sha512": "4b904f0058d316db4f16a3e34289387c0366216614b3eda2b08d74bd45187fac2dbc205090aec9ca45cda5a158887ff423758083381ec3151874ff7b249566dc",
          "sha256": "a9f894d270480e0d936ad7d588ffcbf98d3933c2693419094d5c5563b6b56aa2",
          "sha1": "6551e1f2ef21600a9638d2379e931c5aad1ad61f",
          "md5": "a783c7e098037f5a9d65a0155729c007"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.26.jar",
          "url": "report-generator-jvm-1.0.26.jar",
          "size": 284650,
          "sha512": "4b904f0058d316db4f16a3e34289387c0366216614b3eda2b08d74bd45187fac2dbc205090aec9ca45cda5a158887ff423758083381ec3151874ff7b249566dc",
          "sha256": "a9f894d270480e0d936ad7d588ffcbf98d3933c2693419094d5c5563b6b56aa2",
          "sha1": "6551e1f2ef21600a9638d2379e931c5aad1ad61f",
          "md5": "a783c7e098037f5a9d65a0155729c007"
        }
      ]
    }
  ]
}
