{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.8/report-generator-1.0.8.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.8.jar",
          "url": "report-generator-jvm-1.0.8.jar",
          "size": 169081,
          "sha512": "178a02f0b9e6d29a8c6ae1924ecdb6339e1f93c5a74af365d9f453019121ab7dd7f050a8090f050a7e3191e37af0437172a55201d4a249f52f448318d8f451d1",
          "sha256": "0f31946c6f863ede3efd8b9486335a98e0efb79a9f759039fad054c29d7018db",
          "sha1": "96835e72592ec66ce37ed4203bfd0eb512679533",
          "md5": "a7b13f86e60e10708ee94fad5b6cc95b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.8.jar",
          "url": "report-generator-jvm-1.0.8.jar",
          "size": 169081,
          "sha512": "178a02f0b9e6d29a8c6ae1924ecdb6339e1f93c5a74af365d9f453019121ab7dd7f050a8090f050a7e3191e37af0437172a55201d4a249f52f448318d8f451d1",
          "sha256": "0f31946c6f863ede3efd8b9486335a98e0efb79a9f759039fad054c29d7018db",
          "sha1": "96835e72592ec66ce37ed4203bfd0eb512679533",
          "md5": "a7b13f86e60e10708ee94fad5b6cc95b"
        }
      ]
    }
  ]
}
