{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.11/report-generator-1.0.11.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.11.jar",
          "url": "report-generator-jvm-1.0.11.jar",
          "size": 188388,
          "sha512": "faa9a279cef42d06354014691b560b4fff4aca12a439ed8537cb3fc5a9919912a87d8232102417b0f853954b09016bdd5e932d5dd332479d67e365f3c5c5c5f5",
          "sha256": "db400da1050305169037ae4d7352d88c967a7312079f18748ccbd828468aabe0",
          "sha1": "35268d2022ec05fdc898835ea7a30d5417b6758d",
          "md5": "a4f0e80cdd40384f1082883692938113"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.11.jar",
          "url": "report-generator-jvm-1.0.11.jar",
          "size": 188388,
          "sha512": "faa9a279cef42d06354014691b560b4fff4aca12a439ed8537cb3fc5a9919912a87d8232102417b0f853954b09016bdd5e932d5dd332479d67e365f3c5c5c5f5",
          "sha256": "db400da1050305169037ae4d7352d88c967a7312079f18748ccbd828468aabe0",
          "sha1": "35268d2022ec05fdc898835ea7a30d5417b6758d",
          "md5": "a4f0e80cdd40384f1082883692938113"
        }
      ]
    }
  ]
}
