{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.14/report-generator-1.0.14.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jslegacy-1.0.14.jar",
          "url": "report-generator-js-1.0.14.jar",
          "size": 19985,
          "sha512": "46afce4375f724c394552c6d5502331ffff18adf337b60e6dbf5c97f0fa8decca8e04ae3b982297be20fc27ba01293223b345de24226d6927fcf95954817b729",
          "sha256": "9c1e99c61cbd2f99f9e0107f04bd6154c011aeba14854e64cdc1825cd2f76418",
          "sha1": "0afaa86fd34fca42d2ead6f53e1f0bfa8c1e5d8e",
          "md5": "ad16ee903072cfc671a9f7ed47042fc2"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jslegacy-1.0.14.jar",
          "url": "report-generator-js-1.0.14.jar",
          "size": 19985,
          "sha512": "46afce4375f724c394552c6d5502331ffff18adf337b60e6dbf5c97f0fa8decca8e04ae3b982297be20fc27ba01293223b345de24226d6927fcf95954817b729",
          "sha256": "9c1e99c61cbd2f99f9e0107f04bd6154c011aeba14854e64cdc1825cd2f76418",
          "sha1": "0afaa86fd34fca42d2ead6f53e1f0bfa8c1e5d8e",
          "md5": "ad16ee903072cfc671a9f7ed47042fc2"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jsir-1.0.14.klib",
          "url": "report-generator-js-1.0.14.klib",
          "size": 49522,
          "sha512": "09929133168285d9ca255ede8bee32095920104cc35bb9c2cb78a54cdf47ffbbafe5225c838bfbcd5317699117b11ff7fbd9357c2188aae42bdc44fe747076b2",
          "sha256": "5764aac21c81ed10fd39143ef514842e6fa3be0181abea1cc02cd458626c9e3b",
          "sha1": "8e46d71f771087cd417fa8d1703b0a41bf8173f8",
          "md5": "6cc5d5b2256af713966037eb96b9bb6a"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jsir-1.0.14.klib",
          "url": "report-generator-js-1.0.14.klib",
          "size": 49522,
          "sha512": "09929133168285d9ca255ede8bee32095920104cc35bb9c2cb78a54cdf47ffbbafe5225c838bfbcd5317699117b11ff7fbd9357c2188aae42bdc44fe747076b2",
          "sha256": "5764aac21c81ed10fd39143ef514842e6fa3be0181abea1cc02cd458626c9e3b",
          "sha1": "8e46d71f771087cd417fa8d1703b0a41bf8173f8",
          "md5": "6cc5d5b2256af713966037eb96b9bb6a"
        }
      ]
    }
  ]
}
