{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.16/report-generator-1.0.16.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jslegacy-1.0.16.jar",
          "url": "report-generator-js-1.0.16.jar",
          "size": 75799,
          "sha512": "167d9628ae50f53d2c04759e731f6cb8c765cc6f52c70c890810888a9aac262d7432a59377e098fe69e4692416a159f855354c994cc7d9f72b56fa09913505a0",
          "sha256": "e080f86cba5cb3c6e9cb1b0e24c350716c8996e1587af1d5601ccd49e19f02d4",
          "sha1": "94693a3403c6d1007d710f7ed593f6eaccb86625",
          "md5": "785262eca0315cf098dabf469bd55f50"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jslegacy-1.0.16.jar",
          "url": "report-generator-js-1.0.16.jar",
          "size": 75799,
          "sha512": "167d9628ae50f53d2c04759e731f6cb8c765cc6f52c70c890810888a9aac262d7432a59377e098fe69e4692416a159f855354c994cc7d9f72b56fa09913505a0",
          "sha256": "e080f86cba5cb3c6e9cb1b0e24c350716c8996e1587af1d5601ccd49e19f02d4",
          "sha1": "94693a3403c6d1007d710f7ed593f6eaccb86625",
          "md5": "785262eca0315cf098dabf469bd55f50"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jsir-1.0.16.klib",
          "url": "report-generator-js-1.0.16.klib",
          "size": 99101,
          "sha512": "d5f28d048772ac920633ff3cb26d19670464227ea36bc3909f1d25d40872993712504c347f2072d22a125a4d952356ffcd736bda077b105ea7da735ac6bd1655",
          "sha256": "c82723a864eecb67dd92eedad46f600d9dfb1881273469670cadf743d3f2d0fd",
          "sha1": "c0378e7f3bcaebc82db1ee6b075f573c5c159bf0",
          "md5": "5cacfd9bebc6e36527a0d4e2fda9cce3"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jsir-1.0.16.klib",
          "url": "report-generator-js-1.0.16.klib",
          "size": 99101,
          "sha512": "d5f28d048772ac920633ff3cb26d19670464227ea36bc3909f1d25d40872993712504c347f2072d22a125a4d952356ffcd736bda077b105ea7da735ac6bd1655",
          "sha256": "c82723a864eecb67dd92eedad46f600d9dfb1881273469670cadf743d3f2d0fd",
          "sha1": "c0378e7f3bcaebc82db1ee6b075f573c5c159bf0",
          "md5": "5cacfd9bebc6e36527a0d4e2fda9cce3"
        }
      ]
    }
  ]
}
