{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.16/report-generator-1.0.16.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.16.jar",
          "url": "report-generator-jvm-1.0.16.jar",
          "size": 264469,
          "sha512": "91767674053898f6746816a02e38214b9ab8b7bb33ac3fa7674e1a09b5595ff9dcce4b6b1046fec4435e2bf312573fb2e4693a67dcb02dbf137013e6a0743d34",
          "sha256": "1ce62bc1daefc3d20cd64582142bfe3f8ee604baff8e5c9d970d7620fc61a663",
          "sha1": "a61ec3f93b2701bcc93c8bb8b66ad46de37bb8d6",
          "md5": "7c10a5593f4287fc50bbf2514216d1a2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.16.jar",
          "url": "report-generator-jvm-1.0.16.jar",
          "size": 264469,
          "sha512": "91767674053898f6746816a02e38214b9ab8b7bb33ac3fa7674e1a09b5595ff9dcce4b6b1046fec4435e2bf312573fb2e4693a67dcb02dbf137013e6a0743d34",
          "sha256": "1ce62bc1daefc3d20cd64582142bfe3f8ee604baff8e5c9d970d7620fc61a663",
          "sha1": "a61ec3f93b2701bcc93c8bb8b66ad46de37bb8d6",
          "md5": "7c10a5593f4287fc50bbf2514216d1a2"
        }
      ]
    }
  ]
}
