{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.16/report-generator-1.0.16.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.16.jar",
          "url": "report-generator-jvm-1.0.16.jar",
          "size": 271374,
          "sha512": "62b1e9fe91a45a416cab19357774b628d7701aa0e9531025cdedd49cb383f61674fa3d392d8502176bc5506d9765f2ae66e62046b00b18448b41264d30c1b0e6",
          "sha256": "6c4824455436d0786f65a8dc95fca5279c7a548250a414318d246a35f03961dd",
          "sha1": "df0d7ad8ca3f7c8ce7501d93668109b19d7622b5",
          "md5": "03e5e0dbca9a2016c60a31da93eebd4d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.16.jar",
          "url": "report-generator-jvm-1.0.16.jar",
          "size": 271374,
          "sha512": "62b1e9fe91a45a416cab19357774b628d7701aa0e9531025cdedd49cb383f61674fa3d392d8502176bc5506d9765f2ae66e62046b00b18448b41264d30c1b0e6",
          "sha256": "6c4824455436d0786f65a8dc95fca5279c7a548250a414318d246a35f03961dd",
          "sha1": "df0d7ad8ca3f7c8ce7501d93668109b19d7622b5",
          "md5": "03e5e0dbca9a2016c60a31da93eebd4d"
        }
      ]
    }
  ]
}
