{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.16/report-generator-1.0.16.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.16.jar",
          "url": "report-generator-jvm-1.0.16.jar",
          "size": 273342,
          "sha512": "7f0ab32bb812f0d605b30d78730e445a77613a046b263986adabba01e6d3acd0d5dfa6bf01712573fdab576be1b393cfda72db0bee16c56d3d7fb30540cabf79",
          "sha256": "b80f34777f4c75f8879bb16ed9b222b377c5c60042bed81b26be06d4e4e0b0b4",
          "sha1": "8b39e8cbf551b34f627eeb366cdc336ce69984a0",
          "md5": "0744105bb3b5623de2cf9aa95a0a9d91"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.16.jar",
          "url": "report-generator-jvm-1.0.16.jar",
          "size": 273342,
          "sha512": "7f0ab32bb812f0d605b30d78730e445a77613a046b263986adabba01e6d3acd0d5dfa6bf01712573fdab576be1b393cfda72db0bee16c56d3d7fb30540cabf79",
          "sha256": "b80f34777f4c75f8879bb16ed9b222b377c5c60042bed81b26be06d4e4e0b0b4",
          "sha1": "8b39e8cbf551b34f627eeb366cdc336ce69984a0",
          "md5": "0744105bb3b5623de2cf9aa95a0a9d91"
        }
      ]
    }
  ]
}
