{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.17/report-generator-1.0.17.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jslegacy-1.0.17.jar",
          "url": "report-generator-js-1.0.17.jar",
          "size": 33121,
          "sha512": "d0b70a20ac4ffe3550073d9e0b327de84bb36ff966c77bdee41c61c7119cffb767773391012102535d98bc412611cdd665777192ae3950449b593e4a2fb2d503",
          "sha256": "eb6329cc23efcfc10863776caeeea556d4ed76e1a6543a24cb98648a8fe63cef",
          "sha1": "396be8200b00357e8b07c4ce7e18a087603731e7",
          "md5": "c1ab779050103f411e7b7914af6d3a7d"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jslegacy-1.0.17.jar",
          "url": "report-generator-js-1.0.17.jar",
          "size": 33121,
          "sha512": "d0b70a20ac4ffe3550073d9e0b327de84bb36ff966c77bdee41c61c7119cffb767773391012102535d98bc412611cdd665777192ae3950449b593e4a2fb2d503",
          "sha256": "eb6329cc23efcfc10863776caeeea556d4ed76e1a6543a24cb98648a8fe63cef",
          "sha1": "396be8200b00357e8b07c4ce7e18a087603731e7",
          "md5": "c1ab779050103f411e7b7914af6d3a7d"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jsir-1.0.17.klib",
          "url": "report-generator-js-1.0.17.klib",
          "size": 92841,
          "sha512": "afc11101dc8b33d9616403a555e34f7b724de59449bf32f0e8dec4e573bb2aa0cd11167e235d54c8aff166e1a169773d3e1e784d45916e61ee041a857a41d18e",
          "sha256": "a856b98aa1dcc00b830268c4680e482a1e2af0c1f71b0dd2f1de25f1cffcb749",
          "sha1": "b714000a4a844a74970f2d8adaedbb498b3e728d",
          "md5": "186d1123d1d09335b99158d15f03ca38"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jsir-1.0.17.klib",
          "url": "report-generator-js-1.0.17.klib",
          "size": 92841,
          "sha512": "afc11101dc8b33d9616403a555e34f7b724de59449bf32f0e8dec4e573bb2aa0cd11167e235d54c8aff166e1a169773d3e1e784d45916e61ee041a857a41d18e",
          "sha256": "a856b98aa1dcc00b830268c4680e482a1e2af0c1f71b0dd2f1de25f1cffcb749",
          "sha1": "b714000a4a844a74970f2d8adaedbb498b3e728d",
          "md5": "186d1123d1d09335b99158d15f03ca38"
        }
      ]
    }
  ]
}
