{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.1/report-generator-1.0.1.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.1.jar",
          "url": "report-generator-jvm-1.0.1.jar",
          "size": 62799,
          "sha512": "5b687effca16b673e2c7fc9b36ea100494519f24d5465aa86384ceda054314394f12fba85b8d7ec05cc39a41618b7498e267ecc18993ee8abbc7980d07913bb4",
          "sha256": "ee0f7113ea17083ab2732af1496be2d05805c6e5e531a1b58defd21810c87224",
          "sha1": "a2ff053dd03fd72d3a224497546f5099f4a237a1",
          "md5": "10fbd866f6c96ca9910fc48f25dbdec9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.1.jar",
          "url": "report-generator-jvm-1.0.1.jar",
          "size": 62799,
          "sha512": "5b687effca16b673e2c7fc9b36ea100494519f24d5465aa86384ceda054314394f12fba85b8d7ec05cc39a41618b7498e267ecc18993ee8abbc7980d07913bb4",
          "sha256": "ee0f7113ea17083ab2732af1496be2d05805c6e5e531a1b58defd21810c87224",
          "sha1": "a2ff053dd03fd72d3a224497546f5099f4a237a1",
          "md5": "10fbd866f6c96ca9910fc48f25dbdec9"
        }
      ]
    }
  ]
}
