{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.25/report-generator-1.0.25.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.25.jar",
          "url": "report-generator-jvm-1.0.25.jar",
          "size": 284650,
          "sha512": "22c0c38b7b4e87162c6ac490fb8b26e96e739082d0e56ae2c11904e3777404b2ad1eb1e2359a9f80ccc553b4f8fe09b4a49815ee5963d3a748e1f81a945653e0",
          "sha256": "29f4b9c4675e9847523bc107351e4fd742d2211faafa019cb6616d366de80a98",
          "sha1": "2e88d569cda42910b9143afcf44d9264c0e51d3a",
          "md5": "80e83368216e48e76a213f7860aa7a45"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.25.jar",
          "url": "report-generator-jvm-1.0.25.jar",
          "size": 284650,
          "sha512": "22c0c38b7b4e87162c6ac490fb8b26e96e739082d0e56ae2c11904e3777404b2ad1eb1e2359a9f80ccc553b4f8fe09b4a49815ee5963d3a748e1f81a945653e0",
          "sha256": "29f4b9c4675e9847523bc107351e4fd742d2211faafa019cb6616d366de80a98",
          "sha1": "2e88d569cda42910b9143afcf44d9264c0e51d3a",
          "md5": "80e83368216e48e76a213f7860aa7a45"
        }
      ]
    }
  ]
}
