{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.25/report-generator-1.0.25.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.25.jar",
          "url": "report-generator-jvm-1.0.25.jar",
          "size": 328210,
          "sha512": "f8e3c4ba714b8267eeaf0d614cfe5a3415040f80a3c075dd44848b8af2a0da14541ccc1e55729cdd910691efa8ecfe0fa5ab407890d53269ec30e6d8888e7f00",
          "sha256": "6e07e47bf6e20d6ecbb7173712a2a7b43d32aaf5ee0334a7507fd5892f0efae9",
          "sha1": "90ba5e7194b07990462a9b4209cd37bde272557b",
          "md5": "0d128cedd496bd4981f71181810ea12b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.25.jar",
          "url": "report-generator-jvm-1.0.25.jar",
          "size": 328210,
          "sha512": "f8e3c4ba714b8267eeaf0d614cfe5a3415040f80a3c075dd44848b8af2a0da14541ccc1e55729cdd910691efa8ecfe0fa5ab407890d53269ec30e6d8888e7f00",
          "sha256": "6e07e47bf6e20d6ecbb7173712a2a7b43d32aaf5ee0334a7507fd5892f0efae9",
          "sha1": "90ba5e7194b07990462a9b4209cd37bde272557b",
          "md5": "0d128cedd496bd4981f71181810ea12b"
        }
      ]
    }
  ]
}
