@host = http://localhost:8080/matchbox/fhir
### @host = https://test.ahdis.ch/matchbox/fhir

### Check if server is available
GET {{host}}/metadata HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Origin: http://localhost

### check list of IG's
GET {{host}}/ImplementationGuide HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Origin: http://localhost

### verify that StructureDefinintion is there
GET {{host}}/StructureDefinition?url=http://hl7.org/cda/stds/core/StructureDefinition/ClinicalDocument HTTP/1.1

### verify that StructureDefinintion is there
GET {{host}}/StructureDefinition/ClinicalDocument HTTP/1.1


### upload test structure map for observation
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./matchbox-engine/src/test/resources/cda/datatypes.map

### upload test structure map for observation
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./matchbox-engine/src/test/resources/cda/FullHeader.map


### upload test structure map for observation
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ./matchbox-engine/src/test/resources/cda/LabBody.map

### transform cda enty observation
POST {{host}}/StructureMap/$transform?source=http://salute.gov.it/ig/cda-fhir-maps/StructureMap/RefertodilaboratorioFULLBODY HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml

< ./matchbox-engine/src/test/resources/cda/cda-it.xml