@host = http://localhost:8080/matchboxv3/fhir
### @host = https://test.ahdis.ch/matchboxv3/fhir

### returns metadata confiugraiotn fo server
GET {{host}}/metadata HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Origin: http://localhost


### FHIR Tutorial

POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml
Content-Type: text/fhir-mapping

map "http://ahdis.ch/matchbox/fml/qr2patgender" = "qr2patgender"
uses "http://hl7.org/fhir/StructureDefinition/QuestionnaireResponse" alias QuestionnaireResponse as source
uses "http://hl7.org/fhir/StructureDefinition/Patient" alias Patient as target
group QuestionnaireResponse(source src : QuestionnaireResponse, target tgt : Patient) {
  src.item as item -> tgt as patient then item(item, patient);
}
group item(source src, target tgt: Patient) {
  src.item as item where linkId.value in ('patient.sex') -> tgt.gender = (item.answer.valueString);
}

### FHIR Tutorial
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../matchbox-engine/src/test/resources/tutorial/step1/map/step1.map

###
// cannot use comment like below in map file because it is considered as comment in RESTClient
/// url = 'http://ahdis.ch/matchbox/fml/tutorial-left1'
/// name = 'tutorial-step1'
/// title = 'Tutorial Step 1'

uses "http://hl7.org/fhir/StructureDefinition/tutorial-left1" alias TLeft1 as source
uses "http://hl7.org/fhir/StructureDefinition/tutorial-right1" alias TRight1 as target

group tutorial(source src : TLeft1, target tgt : TRight1) {
    src.a as a -> tgt.a = a "rule_a";
}


### FHIR Tutorial Step 2: Note this is created in a FHIR Engine configured with R5, even though the FHIR API is R4
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml
Content-Type: text/fhir-mapping;fhirVersion=5.0.0

< ../matchbox-engine/src/test/resources/tutorial/step2/map/step2.map



### FHIR Tutorial Step 1
GET {{host}}/StructureMap/tutorial-step1 HTTP/1.1
Accept: application/fhir+xml

### FHIR Tutorial Step 2 (machbox release 3.2.0: you will get back a Content-Type: application/fhir+xml;fhirVersion=5.0.0-draft-final;charset=UTF-8
### this might change in a future version that we honor alos the fhirVersion parameter in the Accept header

GET {{host}}/StructureMap/tutorial-step2 HTTP/1.1
Accept: application/fhir+xml


### FHIR Tutorial
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml
Content-Type: text/fhir-mapping

< ../matchbox-engine/src/test/resources/qr2patgender.map

### FHIR Tutorial
GET {{host}}/StructureMap/qr2patgender HTTP/1.1
Accept: application/fhir+xml


###
POST {{host}}/StructureMap/$transform?source=http://ahdis.ch/matchbox/fml/qr2patgender
Accept: application/fhir+json
Content-Type: application/fhir+json

{
  "resourceType": "QuestionnaireResponse",
  "id": "qrpatientsexeresponse",
  "questionnaire": "http://ahdis.ch/matchbox/fml/qr2patgender",
  "status": "in-progress",
  "item": [
    {
      "linkId": "patient",
      "text": "Patient",
      "item": [
        {
          "linkId": "patient.sex",
          "text": "Geschlecht",
          "answer": [
            {
              "valueString": "male"
            }
          ]
        }
      ]
    }
  ]
}

### POST QuestionnaireResponse

PUT {{host}}/Questionnaire/qrpatientsex
Accept: application/fhir+xml
Content-Type: application/fhir+xml

< ./examples/qrpatient.xml

### POST QuestionnaireResponse

GET {{host}}/Questionnaire/qrpatientsex
Accept: application/fhir+xml;fhirVersion=4.0


### SDDC Extraction
POST {{host}}/QuestionnaireResponse/$extract
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

{
  "resourceType": "QuestionnaireResponse",
  "id": "qrpatientsexeresponse",
  "questionnaire": "http://ahdis.ch/matchbox/fml/qrpatientsex",
  "status": "in-progress",
  "item": [
    {
      "linkId": "patient",
      "text": "Patient",
      "item": [
        {
          "linkId": "patient.sex",
          "text": "Geschlecht",
          "answer": [
            {
              "valueString": "female"
            }
          ]
        }
      ]
    }
  ]
}


