@host = https://test.ahdis.ch/matchboxv3/fhir
### @host = http://localhost:8083/matchboxv3/fhir
### @host = http://hapi.fhir.org/baseR4
### @host = http://localhost:18002/eprik-fhir/camel/matchbox/matchboxv3/fhir


### Check that validation service is up
GET {{host}}/metadata HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json

### OK Testcase Validate Patient ok
POST {{host}}/$validate?profile=http://hl7.org/fhir/StructureDefinition/Patient HTTP/1.1
Content-Type: application/fhir+xml

<Patient xmlns="http://hl7.org/fhir">
  <name>
    <family value="Test"/>
  </name>
</Patient>

### STRUCTURE TESTS XML

### -> Invalid Content
### <- error/invalid: The XML encoding is invalid (must be UTF-8), fatal/invalid: Content is not allowed in prolog. 
POST {{host}}/$validate?profile=http://hl7.org/fhir/StructureDefinition/Patient HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+xml

Hello validator

### -> Wrong format: Missing namespace
### <- fatal / structure : This content cannot be parsed (unknown or unrecognized XML Root element namespace/name 'noNamespace::Patient)'
POST {{host}}/$validate?profile=http://hl7.org/fhir/StructureDefinition/Patient HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+xml

<Patient>
  <name>
    <family value="Test"/>
  </name>
</Patient>

### -> Wrong format: Text in element tag
### <- error / structure : "Text should not be present ('Test')"
### <- error / invariant : ""Constraint failed: ele-1: 'All FHIR elements must have a @value or children' (defined in http://hl7.org/fhir/StructureDefinition/Element)""
### <- error / invalid: "Primitive types must have a value or must have child extensions"
POST {{host}}/$validate?profile=http://hl7.org/fhir/StructureDefinition/Patient HTTP/1.1
Content-Type: application/fhir+xml

<Patient xmlns="http://hl7.org/fhir">
  <name>
    <family>Test</family>
  </name>
</Patient>

### -> Wrong element: test not allowed
### error / structure : Undefined element 'test' at /f:Patient
POST {{host}}/$validate?profile=http://hl7.org/fhir/StructureDefinition/Patient HTTP/1.1
Content-Type: application/fhir+xml

<Patient xmlns="http://hl7.org/fhir">
  <test value="true" />
</Patient>

### -> Wrong element: test not allowed
### error / structure : Undefined element 'test' at /f:Patient
POST {{host}}/$validate?profile=http://hl7.org/fhir/StructureDefinition/Patient HTTP/1.1
Content-Type: application/fhir+xml

<Patient xmlns="http://hl7.org/fhir">
  <test value="true" />
</Patient>

### -> Wrong element order: g
### <- error / invalid: "Primitive types must have a value or must have child extensions"
POST {{host}}/$validate?profile=http://hl7.org/fhir/StructureDefinition/Patient HTTP/1.1
Content-Type: application/fhir+xml

<Patient xmlns="http://hl7.org/fhir">
  <gender value="male" />
  <name>
    <family value="Test" />
  </name>
</Patient>


### IPS minimal
POST {{host}}/$validate?profile=http://hl7.org/fhir/uv/ips/StructureDefinition/Bundle-uv-ips HTTP/1.1
Content-Type: application/fhir+json

< .≈ips-minimal.json


### IPS not birthdate
POST {{host}}/$validate?profile=http://hl7.org/fhir/uv/ips/StructureDefinition/Bundle-uv-ips HTTP/1.1
Content-Type: application/fhir+json

< ./examples/ips-minimal-err-patnobirthdate.json


### lenient-display-validation does not work with displayLanguage de-CH: "Wrong Display Name 'PRESCRIPTIONS' for http://loinc.org#57828-6. There are no valid display names found for language(s) 'de-CH'. Default display is 'Prescription list'
POST http://tx.fhir.org/r4/CodeSystem/$validate-code? HTTP/1.0
User-Agent: hapi-fhir-tooling-client
Accept: application/fhir+json; fhirVersion=4.0
Content-Type: application/fhir+json; fhirVersion=4.0;charset=UTF-8

{"resourceType":"Parameters","parameter":[{"name":"coding","valueCoding":{"system":"http://loinc.org","code":"57828-6","display":"PRESCRIPTIONS"}},{"name":"displayLanguage","valueString":"de-CH"},{"name":"lenient-display-validation","valueBoolean":true},{"name":"default-to-latest-version","valueBoolean":true},{"name":"cache-id","valueId":"5ccc8cc7-c61a-49cd-b8f6-b2c8899b2ee4"},{"name":"profile-url","valueString":"http://hl7.org/fhir/ExpansionProfile/dc8fd4bc-091a-424a-8a3b-6198ef146891"},{"name":"mode","valueString":"lenient-display-validation"},{"name":"diagnostics","valueBoolean":true}]}


### lenient-display-validation works with displayLanguage en-US
POST http://tx.fhir.org/r4/CodeSystem/$validate-code? HTTP/1.0
User-Agent: hapi-fhir-tooling-client
Accept: application/fhir+json; fhirVersion=4.0
Content-Type: application/fhir+json; fhirVersion=4.0;charset=UTF-8

{"resourceType":"Parameters","parameter":[{"name":"coding","valueCoding":{"system":"http://loinc.org","code":"57828-6","display":"PRESCRIPTIONS"}},{"name":"displayLanguage","valueString":"en-US"},{"name":"lenient-display-validation","valueBoolean":true},{"name":"default-to-latest-version","valueBoolean":true},{"name":"cache-id","valueId":"5ccc8cc7-c61a-49cd-b8f6-b2c8899b2ee4"},{"name":"profile-url","valueString":"http://hl7.org/fhir/ExpansionProfile/dc8fd4bc-091a-424a-8a3b-6198ef146891"},{"name":"mode","valueString":"lenient-display-validation"},{"name":"diagnostics","valueBoolean":true}]}

