{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.22/report-generator-1.0.22.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.22.jar",
          "url": "report-generator-jvm-1.0.22.jar",
          "size": 323722,
          "sha512": "126003787819a2e780a83de45e08bdd35fa6feb99c8238771a38a47f1699e34779e4ef5620e60afe7314009333d214cda97e34e29ffcc075931bd8d89ab6630f",
          "sha256": "ec63a2963c658da93add11e5192377721c027f06e61a5d42cefa737683e2efa2",
          "sha1": "50dc229e7842b11fa54c3954ca3148ae59188304",
          "md5": "c325012ec2ddedec6a5bb675b4d84cd8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.22.jar",
          "url": "report-generator-jvm-1.0.22.jar",
          "size": 323722,
          "sha512": "126003787819a2e780a83de45e08bdd35fa6feb99c8238771a38a47f1699e34779e4ef5620e60afe7314009333d214cda97e34e29ffcc075931bd8d89ab6630f",
          "sha256": "ec63a2963c658da93add11e5192377721c027f06e61a5d42cefa737683e2efa2",
          "sha1": "50dc229e7842b11fa54c3954ca3148ae59188304",
          "md5": "c325012ec2ddedec6a5bb675b4d84cd8"
        }
      ]
    }
  ]
}
