{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.13/report-generator-1.0.13.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.13.jar",
          "url": "report-generator-jvm-1.0.13.jar",
          "size": 222325,
          "sha512": "c4dae18514718507bbd14e2a7995d135ab9180222b641339970cfe577bada5973af511bc9cbc3dd0401b8b14b680b58b15607111594be5115fdd683f8dc0c77e",
          "sha256": "b1cc4c2679b715e595e70c3176b50ad7a54a91205c49eddd30d04cc0853ca7d8",
          "sha1": "a87c28d1cc2115779aa09d37241a175df0dd4655",
          "md5": "6fe6458b4bde60d9662f45788ee6ae66"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.13.jar",
          "url": "report-generator-jvm-1.0.13.jar",
          "size": 222325,
          "sha512": "c4dae18514718507bbd14e2a7995d135ab9180222b641339970cfe577bada5973af511bc9cbc3dd0401b8b14b680b58b15607111594be5115fdd683f8dc0c77e",
          "sha256": "b1cc4c2679b715e595e70c3176b50ad7a54a91205c49eddd30d04cc0853ca7d8",
          "sha1": "a87c28d1cc2115779aa09d37241a175df0dd4655",
          "md5": "6fe6458b4bde60d9662f45788ee6ae66"
        }
      ]
    }
  ]
}
