{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.12/report-generator-1.0.12.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.12.jar",
          "url": "report-generator-jvm-1.0.12.jar",
          "size": 205395,
          "sha512": "23d007c3dedca7c2ce8a86081826517d56731b4bef27484e27c4ebcd065c53298d70dabda9d4a72c88211aa8330e312236f6a99f2642e927a86d21659d2695c1",
          "sha256": "feb54427691b6d10241e900668c8c55a167a29f6b52f6065b55ba0e6d20f70f3",
          "sha1": "0128da9855f52022fc1b2a8c6f065ab456f74b40",
          "md5": "39b8b2fcc31ee6272765669a7d718294"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.12.jar",
          "url": "report-generator-jvm-1.0.12.jar",
          "size": 205395,
          "sha512": "23d007c3dedca7c2ce8a86081826517d56731b4bef27484e27c4ebcd065c53298d70dabda9d4a72c88211aa8330e312236f6a99f2642e927a86d21659d2695c1",
          "sha256": "feb54427691b6d10241e900668c8c55a167a29f6b52f6065b55ba0e6d20f70f3",
          "sha1": "0128da9855f52022fc1b2a8c6f065ab456f74b40",
          "md5": "39b8b2fcc31ee6272765669a7d718294"
        }
      ]
    }
  ]
}
