{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.12/report-generator-1.0.12.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.12.jar",
          "url": "report-generator-jvm-1.0.12.jar",
          "size": 211412,
          "sha512": "435fb7ada2552f290a6abe1a2dfe2cc0a98a2caffe66d651038ae5f1d235c63cc038796ce6bfa1f89474d4cb97acf15e4c76842167a69cd78f56982c0f3e0e3f",
          "sha256": "b509120a491c2d522ba46e0d929c66dc0ad083ef4ce3998ad4bd2bf3911a3de2",
          "sha1": "000d108aef470c0aa2bd33a87e9afc0e0ca78743",
          "md5": "cce071a5cd4b1b2817c140b6445c81a5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.12.jar",
          "url": "report-generator-jvm-1.0.12.jar",
          "size": 211412,
          "sha512": "435fb7ada2552f290a6abe1a2dfe2cc0a98a2caffe66d651038ae5f1d235c63cc038796ce6bfa1f89474d4cb97acf15e4c76842167a69cd78f56982c0f3e0e3f",
          "sha256": "b509120a491c2d522ba46e0d929c66dc0ad083ef4ce3998ad4bd2bf3911a3de2",
          "sha1": "000d108aef470c0aa2bd33a87e9afc0e0ca78743",
          "md5": "cce071a5cd4b1b2817c140b6445c81a5"
        }
      ]
    }
  ]
}
