{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.12/report-generator-1.0.12.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.12.jar",
          "url": "report-generator-jvm-1.0.12.jar",
          "size": 198626,
          "sha512": "4a865db875ba19e5de3b4e5b9203d2c0799a41ded8e6b4f25dc52073465b634bd6e41b823ecac69ea060500e70fa22b9b662bc2068c74ac78b4152a90bbb8faa",
          "sha256": "56528cb99eee41f6e42d69afb23e96cdb4289beb911572d952cb7d122834c84f",
          "sha1": "0756bc59d380d401ac42be4e5eb5a12bd6df27a8",
          "md5": "9be60ac80133f979756f7dbd42031588"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.12.jar",
          "url": "report-generator-jvm-1.0.12.jar",
          "size": 198626,
          "sha512": "4a865db875ba19e5de3b4e5b9203d2c0799a41ded8e6b4f25dc52073465b634bd6e41b823ecac69ea060500e70fa22b9b662bc2068c74ac78b4152a90bbb8faa",
          "sha256": "56528cb99eee41f6e42d69afb23e96cdb4289beb911572d952cb7d122834c84f",
          "sha1": "0756bc59d380d401ac42be4e5eb5a12bd6df27a8",
          "md5": "9be60ac80133f979756f7dbd42031588"
        }
      ]
    }
  ]
}
