server:
  servlet:
    context-path: /matchboxv3
hapi:
  fhir:
    server_address: http://localhost:8080/matchboxv3/fhir
    implementationguides:
      fhir_r4_core:
        name: hl7.fhir.r4.core
        version: 4.0.1
        url: classpath:/hl7.fhir.r4.core.tgz
      fhir_terminology:
        name: hl7.terminology.r4
        version: 6.2.0
        url: classpath:/hl7.terminology.r4#6.2.0.tgz
      fhir_extensions:
        name: hl7.fhir.uv.extensions
        version: 1.0.0
        url: classpath:/hl7.fhir.uv.extensions#1.0.0.tgz
matchbox:
  fhir:
    context:
      fhirVersion: 4.0.1
      txServer: https://smt.esante.gouv.fr/fhir/
      txLog: tx.html
      txUseEcosystem: false
      suppressWarnInfo:
        hl7.fhir.r4.core#4.0.1:
          - "Constraint failed: dom-6:"
