{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.19/report-generator-1.0.19.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.19.jar",
          "url": "report-generator-jvm-1.0.19.jar",
          "size": 322715,
          "sha512": "b1c39ed28293b10f58f6aa62270e65fa4a87bd914132281e210202120feb77f2cd475d2e95694c5d92b5ead051069df5039b175ff3290079d6b38fe34cfa5690",
          "sha256": "e177199e391c55cbf30e1c48eb0777b650594564d038a4065ad3590399799361",
          "sha1": "4e77a89e14f4f4c5a3b7aa2f9e8112dfb887baa7",
          "md5": "6a860bcec7dae919450e1954cfd6775c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.19.jar",
          "url": "report-generator-jvm-1.0.19.jar",
          "size": 322715,
          "sha512": "b1c39ed28293b10f58f6aa62270e65fa4a87bd914132281e210202120feb77f2cd475d2e95694c5d92b5ead051069df5039b175ff3290079d6b38fe34cfa5690",
          "sha256": "e177199e391c55cbf30e1c48eb0777b650594564d038a4065ad3590399799361",
          "sha1": "4e77a89e14f4f4c5a3b7aa2f9e8112dfb887baa7",
          "md5": "6a860bcec7dae919450e1954cfd6775c"
        }
      ]
    }
  ]
}
