{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.19/report-generator-1.0.19.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.19.jar",
          "url": "report-generator-jvm-1.0.19.jar",
          "size": 323122,
          "sha512": "6b2f95af3bee0a57a301eea6a843fc05d9d261aaa281b81c5a73de4885a07ad22c10abb139d6d94bd134300d810528725461b42cd8c5447ed4d9bbdf97eb9b17",
          "sha256": "fa77e1ddf7cbcd99e8ce44e567e39940feff44c82de1296b268d7b8a3300f04c",
          "sha1": "fa85b91afd7b9c6d5607543c8a696d9fe69d96fc",
          "md5": "3552eec0169704c499c3fdd21a1c6595"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.19.jar",
          "url": "report-generator-jvm-1.0.19.jar",
          "size": 323122,
          "sha512": "6b2f95af3bee0a57a301eea6a843fc05d9d261aaa281b81c5a73de4885a07ad22c10abb139d6d94bd134300d810528725461b42cd8c5447ed4d9bbdf97eb9b17",
          "sha256": "fa77e1ddf7cbcd99e8ce44e567e39940feff44c82de1296b268d7b8a3300f04c",
          "sha1": "fa85b91afd7b9c6d5607543c8a696d9fe69d96fc",
          "md5": "3552eec0169704c499c3fdd21a1c6595"
        }
      ]
    }
  ]
}
