{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.16/report-generator-1.0.16.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator.klib",
          "url": "report-generator-native-1.0.16.klib",
          "size": 90365,
          "sha512": "0a81814a863dfc2014858b38f66a4cebe04414fad36331bbde7336fdd98bdb4fd4ea31f5c345ad2c7b742a22c8ff1d702e2291b488025232a151649455c1d024",
          "sha256": "847784df7baecd975f0d6204e3bcbcbb96fbc6c0d3dd6969cfa4ee493509eb89",
          "sha1": "769d8ffa5e5d07b7be7329e42e25d597ac9f1935",
          "md5": "2b51a2e3e4df5cfd71cd0fa094355580"
        }
      ]
    },
    {
      "name": "nativeMetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-native-1.0.16-metadata.jar",
          "url": "report-generator-native-1.0.16-metadata.jar",
          "size": 261,
          "sha512": "a347cc265929460ea230c7dfeaea3922dbc0c0d6621ae227c7db7fa21fa42ca27ed0c8d127761128f990ed3c5dda7664c8e27e02c9dec7a1f748e92a3a61c675",
          "sha256": "4e8302a58a0871439ef1d07c3193714285525b486fbdfdde4e8b275b4153c103",
          "sha1": "df0b675de9a89c2aa6b56f2cfe57ba91f179581b",
          "md5": "9fc31250663d8a4551ec778c9e2880a9"
        }
      ]
    }
  ]
}
