package ca.uhn.fhir.jpa.starter;

public enum ConfigDefinitionTypes {
	FILTER_DEFINITIONS,
	SCORECARD_DEFINITIONS,
	ANALYTIC_DEFINITIONS,
	LINECHART_DEFINITIONS,
	PIECHART_DEFINITIONS,
	BARCHART_DEFINITIONS,
	TABULARCHART_DEFINITIONS,
	DAILY_SUMMARY_DEFINITIONS
}
