POST http://localhost:8080/fhir/Patient
Content-Type: application/json

{
  "resourceType": "Patient",
  "identifier": [
    {
      "system": "http://example.com/fhir/identifier/my-eid-system",
      "value": "49"
    }
  ],
  "name": [
    {
      "family": "Powers",
      "given": [
        "Austin",
        "Danger"
      ]
    }
  ],
  "gender": "male",
  "birthDate": "1975-02-03"
}

###
