PUT http://localhost:8080/fhir/Patient/A1
Content-Type: application/json

{
  "resourceType": "Patient",
  "id": "A1",
  "identifier": [
    {
      "system": "http://example.com/fhir/identifier/my-eid-system",
      "value": "42"
    }
  ],
  "name": [
    {
      "family": "Powers",
      "given": [
        "Austin"
      ]
    }
  ],
  "gender": "male",
  "birthDate": "1975-02-03"
}

###
