PUT http://localhost:8080/fhir/Patient/C3
Content-Type: application/json

{
  "resourceType": "Patient",
  "id": "C3",
  "identifier": [
    {
      "system": "http://hl7.org/fhir/sid/us-medicare",
      "value": "1EG4-TE5-MK73"
    }
  ],
  "name": [
    {
      "family": "Agnew",
      "given": [
        "Jim"
      ]
    }
  ],
  "gender": "male",
  "birthDate": "1970-01-26"
}

###
