{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.27/report-generator-1.0.27.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.27.jar",
          "url": "report-generator-jvm-1.0.27.jar",
          "size": 348383,
          "sha512": "a9f58c116a8a02d01497aa108664255702e60a63bf4e2719544b8dba68c8f4dad6c24d64b13e9858ca88e06e1f1977ba3c3a7dc103eb887f85b898ff4f6d9fe6",
          "sha256": "8635478357c62d7a3249defa249c2a15acecc4f626c58bec05f5442a4493484e",
          "sha1": "5b8e8f0fc933d366254d9a59aca04c5307b75449",
          "md5": "f4a0739e26886f15274176f644057de8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.27.jar",
          "url": "report-generator-jvm-1.0.27.jar",
          "size": 348383,
          "sha512": "a9f58c116a8a02d01497aa108664255702e60a63bf4e2719544b8dba68c8f4dad6c24d64b13e9858ca88e06e1f1977ba3c3a7dc103eb887f85b898ff4f6d9fe6",
          "sha256": "8635478357c62d7a3249defa249c2a15acecc4f626c58bec05f5442a4493484e",
          "sha1": "5b8e8f0fc933d366254d9a59aca04c5307b75449",
          "md5": "f4a0739e26886f15274176f644057de8"
        }
      ]
    }
  ]
}
