{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.27/report-generator-1.0.27.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.27.jar",
          "url": "report-generator-jvm-1.0.27.jar",
          "size": 351596,
          "sha512": "2a01f75c884aac96b1148ca7a4f1baca2b4c076fb0118a0af1b1b23b22bebe1c5b075825eb4708f46bb81824875d9e5117318ef5e88c2f1e887c9e70ee9e6d9b",
          "sha256": "7be00323f50b632c0d4f4a3f9ed0dfdb879eb686e95c6d0489e6e35a3e53253d",
          "sha1": "3e4488a84a1c52752083ca9916bc78ff203e1d96",
          "md5": "c70dbde4b8a2c6bc21a4be4403014ee3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.27.jar",
          "url": "report-generator-jvm-1.0.27.jar",
          "size": 351596,
          "sha512": "2a01f75c884aac96b1148ca7a4f1baca2b4c076fb0118a0af1b1b23b22bebe1c5b075825eb4708f46bb81824875d9e5117318ef5e88c2f1e887c9e70ee9e6d9b",
          "sha256": "7be00323f50b632c0d4f4a3f9ed0dfdb879eb686e95c6d0489e6e35a3e53253d",
          "sha1": "3e4488a84a1c52752083ca9916bc78ff203e1d96",
          "md5": "c70dbde4b8a2c6bc21a4be4403014ee3"
        }
      ]
    }
  ]
}
