{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.27/report-generator-1.0.27.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.27.jar",
          "url": "report-generator-jvm-1.0.27.jar",
          "size": 330386,
          "sha512": "83c426cbc1ce96ae9883a7cb000fc5f33ed1664f0bfaca077e44b6c9318ac4a6baa1cb3f91f604306984ab7fb5c3f89fbd2cf1121686e6fd8a00ea58c34dbbfe",
          "sha256": "c6e99f1bf3e2afd04614c56f0c389f9d803d260f1070e7f8bc8fd52a5821993a",
          "sha1": "f6fafd9a15907cc826a33c2a77968d4df6fcec9f",
          "md5": "99ad777d339f4dc40dc0a470ab32fff5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.27.jar",
          "url": "report-generator-jvm-1.0.27.jar",
          "size": 330386,
          "sha512": "83c426cbc1ce96ae9883a7cb000fc5f33ed1664f0bfaca077e44b6c9318ac4a6baa1cb3f91f604306984ab7fb5c3f89fbd2cf1121686e6fd8a00ea58c34dbbfe",
          "sha256": "c6e99f1bf3e2afd04614c56f0c389f9d803d260f1070e7f8bc8fd52a5821993a",
          "sha1": "f6fafd9a15907cc826a33c2a77968d4df6fcec9f",
          "md5": "99ad777d339f4dc40dc0a470ab32fff5"
        }
      ]
    }
  ]
}
