{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.15/report-generator-1.0.15.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jslegacy-1.0.15.jar",
          "url": "report-generator-js-1.0.15.jar",
          "size": 21050,
          "sha512": "391003683ff3671c49d095b99b29025a5048077e39dbde7bcd3091952054718682dc034da4ef045795d502810d52a79541d7a7f37cc0bd1151c423b086cfab57",
          "sha256": "e34d053fa9f70074c637c56afb486a3acd7f9dd6a46930ba69880c529d675acc",
          "sha1": "3e8b7b49d4a02ac28e8353ac54cda0852de66d93",
          "md5": "01606b56ffe071b4a16b11a1cf822962"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jslegacy-1.0.15.jar",
          "url": "report-generator-js-1.0.15.jar",
          "size": 21050,
          "sha512": "391003683ff3671c49d095b99b29025a5048077e39dbde7bcd3091952054718682dc034da4ef045795d502810d52a79541d7a7f37cc0bd1151c423b086cfab57",
          "sha256": "e34d053fa9f70074c637c56afb486a3acd7f9dd6a46930ba69880c529d675acc",
          "sha1": "3e8b7b49d4a02ac28e8353ac54cda0852de66d93",
          "md5": "01606b56ffe071b4a16b11a1cf822962"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jsir-1.0.15.klib",
          "url": "report-generator-js-1.0.15.klib",
          "size": 53131,
          "sha512": "bc752a73318a45eb2a183c2aca79c861213b4f78cc97c0f83a1c1b2847461bbb4f34d245a60b02fe058b73c44db41fa5665bab3c6e0752ecd3c7fcb408c79b0d",
          "sha256": "5d561e84d58f7ba3f403533b8a4f8d7f93450c2dead4a47d09d666f21b3891a0",
          "sha1": "b79b582ed18322f050fe73e17f8adeb8fde9bfaa",
          "md5": "1b4ebfbf1af63419b99b50f111752717"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jsir-1.0.15.klib",
          "url": "report-generator-js-1.0.15.klib",
          "size": 53131,
          "sha512": "bc752a73318a45eb2a183c2aca79c861213b4f78cc97c0f83a1c1b2847461bbb4f34d245a60b02fe058b73c44db41fa5665bab3c6e0752ecd3c7fcb408c79b0d",
          "sha256": "5d561e84d58f7ba3f403533b8a4f8d7f93450c2dead4a47d09d666f21b3891a0",
          "sha1": "b79b582ed18322f050fe73e17f8adeb8fde9bfaa",
          "md5": "1b4ebfbf1af63419b99b50f111752717"
        }
      ]
    }
  ]
}
