{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-metadata-1.0.15-all.jar",
          "url": "report-generator-1.0.15-all.jar",
          "size": 8600,
          "sha512": "57fd007a1251cb31a8960d34485357862571cad8ef6ff5f59cdacd9bcec3a8a2f6f368aca72efe7ac0848193ea30d9523e04c0b85198e85ed74520d40987b85d",
          "sha256": "af8a86474d18c40cfd397b0b18d9d95e39d33a03e92c45394d403a57f0030bdd",
          "sha1": "3107894a95c341d99001c02bf6736d8100969653",
          "md5": "a00b8a292735bccbfdc6016f6744dc15"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-1.0.15.jar",
          "url": "report-generator-1.0.15.jar",
          "size": 17196,
          "sha512": "14dce4cee4c7282ee2b502e6704411417ef1a705958d6f3d2c8f34205d0139748a01e4ac53c30be3aa341c21eb893c05ac5eaf833d7e9747da84db3bf832ef06",
          "sha256": "31cbd79a4d502692dd1644902b522e4782f57ce17d73ca04c22929f19b5fcf24",
          "sha1": "bfbb7622db02c3172663450b95b8780c6e195f85",
          "md5": "0b8aa872fc7cdaaab52d14260a079e55"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../report-generator-js/1.0.15/report-generator-js-1.0.15.module",
        "group": "com.iprd.report",
        "module": "report-generator-js",
        "version": "1.0.15"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../report-generator-js/1.0.15/report-generator-js-1.0.15.module",
        "group": "com.iprd.report",
        "module": "report-generator-js",
        "version": "1.0.15"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../report-generator-js/1.0.15/report-generator-js-1.0.15.module",
        "group": "com.iprd.report",
        "module": "report-generator-js",
        "version": "1.0.15"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../report-generator-js/1.0.15/report-generator-js-1.0.15.module",
        "group": "com.iprd.report",
        "module": "report-generator-js",
        "version": "1.0.15"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../report-generator-jvm/1.0.15/report-generator-jvm-1.0.15.module",
        "group": "com.iprd.report",
        "module": "report-generator-jvm",
        "version": "1.0.15"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../report-generator-jvm/1.0.15/report-generator-jvm-1.0.15.module",
        "group": "com.iprd.report",
        "module": "report-generator-jvm",
        "version": "1.0.15"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../report-generator-native/1.0.15/report-generator-native-1.0.15.module",
        "group": "com.iprd.report",
        "module": "report-generator-native",
        "version": "1.0.15"
      }
    },
    {
      "name": "nativeMetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../report-generator-native/1.0.15/report-generator-native-1.0.15.module",
        "group": "com.iprd.report",
        "module": "report-generator-native",
        "version": "1.0.15"
      }
    }
  ]
}
