{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.29/report-generator-1.0.29.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "itext7-core",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.29.jar",
          "url": "report-generator-jvm-1.0.29.jar",
          "size": 326402,
          "sha512": "e533f902cc933e2fb66a27c1986d4060e31ada39f7a374a7d25219a4a8ba70652bd8bfc144637b25faa361477d2f2d7b169893975f7e570bb5cb088cd3c822de",
          "sha256": "786a5e5217feb71697e1e90f4e0b3b544d5c464b4cc357dfae47f753772b4869",
          "sha1": "8c037d00409ab05e6a51d798715eda705a40e514",
          "md5": "5d66ff760b7425ebd64ae4765ce0b8fa"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "itext7-core",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.29.jar",
          "url": "report-generator-jvm-1.0.29.jar",
          "size": 326402,
          "sha512": "e533f902cc933e2fb66a27c1986d4060e31ada39f7a374a7d25219a4a8ba70652bd8bfc144637b25faa361477d2f2d7b169893975f7e570bb5cb088cd3c822de",
          "sha256": "786a5e5217feb71697e1e90f4e0b3b544d5c464b4cc357dfae47f753772b4869",
          "sha1": "8c037d00409ab05e6a51d798715eda705a40e514",
          "md5": "5d66ff760b7425ebd64ae4765ce0b8fa"
        }
      ]
    }
  ]
}
