name: Create iRealisatie release package

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV && echo "PKG_NAME=hapi-fhir-jpaserver-starter" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install -DskipTests=true
      - name: Add version file
        run: 'echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > target/version.json'
      - name: Create tar
        run: tar -czf ${{ env.PKG_NAME }}_${{ env.RELEASE_VERSION }}.tar.gz -C target ROOT.war version.json
      - name: Upload release tar
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKG_NAME }}_${{ env.RELEASE_VERSION }}
          path: ${{ env.PKG_NAME }}_${{ env.RELEASE_VERSION }}.tar.gz
