{
  "formatVersion": "1.1",
  "component": {
    "url": "../../report-generator/1.0.18/report-generator-1.0.18.module",
    "group": "com.iprd.report",
    "module": "report-generator",
    "version": "1.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.18.jar",
          "url": "report-generator-jvm-1.0.18.jar",
          "size": 262755,
          "sha512": "2e9dd70766f3a3d593678cdcd38f7fb21cd0828c9908e9342ec0836a30b2b4488790faf9261cbdb831a83989a1e71cca1df92556b53bd1a991d8e269dee62749",
          "sha256": "7f24cffc7efc64e5a93124d072ba3cda0a8c5feef483f2dc2aa7c2a8416b3817",
          "sha1": "94b14a35d8f774570bcefc9609f11ca15614392a",
          "md5": "2336679ecb0a19bde45b16aa9f8eee4f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-structures-r4",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-validation",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "ca.uhn.hapi.fhir",
          "module": "hapi-fhir-client",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "report-generator-jvm-1.0.18.jar",
          "url": "report-generator-jvm-1.0.18.jar",
          "size": 262755,
          "sha512": "2e9dd70766f3a3d593678cdcd38f7fb21cd0828c9908e9342ec0836a30b2b4488790faf9261cbdb831a83989a1e71cca1df92556b53bd1a991d8e269dee62749",
          "sha256": "7f24cffc7efc64e5a93124d072ba3cda0a8c5feef483f2dc2aa7c2a8416b3817",
          "sha1": "94b14a35d8f774570bcefc9609f11ca15614392a",
          "md5": "2336679ecb0a19bde45b16aa9f8eee4f"
        }
      ]
    }
  ]
}
